export type CommerceBasketLine = Readonly<{ offerId:string; offerVersion:number; skuId:string; quantity:number }>;
export type CommerceBasket = Readonly<{ basketId:string; memberId:string; lines:readonly CommerceBasketLine[] }>;
export type CommitmentPolicy = Readonly<{ minQuantity:number; maxQuantity:number; quantityStep?:number }>;
export type CommitmentRequest = Readonly<{ requestId:string; memberId:string; basketId:string; offerId:string; offerVersion:number; quantity:number }>;
export type AuthoritativeOffer = Readonly<{ offerId:string; version:number; skuId:string; state:'OPEN'|'CLOSED'|'SUSPENDED'; validFrom:string; validUntil:string; policy:CommitmentPolicy }>;
export type DemandCommitment = Readonly<{ commitmentId:string; requestId:string; memberId:string; offerId:string; offerVersion:number; skuId:string; quantity:number; committedAt:string }>;
export type CommitmentDecision = Readonly<{ok:true;commitment:DemandCommitment}>|Readonly<{ok:false;code:'MEMBER_NOT_COMMERCE_ELIGIBLE'|'BASKET_LINE_NOT_FOUND'|'OFFER_NOT_OPEN'|'OFFER_NOT_YET_VALID'|'OFFER_EXPIRED'|'OFFER_VERSION_STALE'|'QUANTITY_BELOW_MINIMUM'|'QUANTITY_ABOVE_MAXIMUM'|'QUANTITY_STEP_INVALID'}>;
function validPositiveInteger(value:number):boolean{return Number.isSafeInteger(value)&&value>0;}
export function validateCommitmentPolicy(policy:CommitmentPolicy):void{if(!validPositiveInteger(policy.minQuantity))throw new Error('MIN_QUANTITY_INVALID');if(!validPositiveInteger(policy.maxQuantity))throw new Error('MAX_QUANTITY_INVALID');if(policy.maxQuantity<policy.minQuantity)throw new Error('MAX_QUANTITY_BELOW_MINIMUM');if(policy.quantityStep!==undefined&&!validPositiveInteger(policy.quantityStep))throw new Error('QUANTITY_STEP_INVALID');}
/** A basket is intent only. Only a replay-safe commitment from a commerce-eligible membership contributes pooled demand. */
export function authorizeDemandCommitment(input:Readonly<{request:CommitmentRequest;basket:CommerceBasket;offer:AuthoritativeOffer;memberCommerceEligible:boolean;now:string;existingByRequestId?:ReadonlyMap<string,DemandCommitment>}>):CommitmentDecision{const {request,basket,offer}=input;const replay=input.existingByRequestId?.get(request.requestId);if(replay)return {ok:true,commitment:replay};if(!input.memberCommerceEligible)return {ok:false,code:'MEMBER_NOT_COMMERCE_ELIGIBLE'};if(offer.state!=='OPEN')return {ok:false,code:'OFFER_NOT_OPEN'};if(request.offerVersion!==offer.version)return {ok:false,code:'OFFER_VERSION_STALE'};const nowMs=Date.parse(input.now);if(!Number.isFinite(nowMs))throw new Error('NOW_INVALID');if(nowMs<Date.parse(offer.validFrom))return {ok:false,code:'OFFER_NOT_YET_VALID'};if(nowMs>=Date.parse(offer.validUntil))return {ok:false,code:'OFFER_EXPIRED'};validateCommitmentPolicy(offer.policy);if(!validPositiveInteger(request.quantity)||request.quantity<offer.policy.minQuantity)return {ok:false,code:'QUANTITY_BELOW_MINIMUM'};if(request.quantity>offer.policy.maxQuantity)return {ok:false,code:'QUANTITY_ABOVE_MAXIMUM'};const step=offer.policy.quantityStep??1;if((request.quantity-offer.policy.minQuantity)%step!==0)return {ok:false,code:'QUANTITY_STEP_INVALID'};const line=basket.lines.find(candidate=>candidate.offerId===request.offerId&&candidate.offerVersion===request.offerVersion&&candidate.quantity===request.quantity);if(!line)return {ok:false,code:'BASKET_LINE_NOT_FOUND'};return {ok:true,commitment:{commitmentId:`commitment:${request.requestId}`,requestId:request.requestId,memberId:request.memberId,offerId:offer.offerId,offerVersion:offer.version,skuId:offer.skuId,quantity:request.quantity,committedAt:input.now}};}
export function pooledDemandQuantity(commitments:readonly DemandCommitment[],offerId:string):number{return commitments.filter(c=>c.offerId===offerId).reduce((sum,c)=>sum+c.quantity,0);}
