import type {AuthorityGrantId,EvidenceId,Money,OfferId,ParticipantId,Quantity,Specification,SpecificationId} from '../../kernel/src/index.js';
import {AuthorityEvaluator} from '../../authority/src/index.js';
import {InMemoryCatalog,type CatalogListing,type MemberOffer,type PriceObservation} from '../../catalog/src/index.js';
import {authorizePricePromise,type FuturePricePromise} from '../../governance/src/index.js';

export interface SalesWindow{readonly id:string;readonly validFrom:string;readonly validUntil:string;readonly pickupPlace:string;readonly active:boolean;readonly policyVersion:string;readonly createdBy:ParticipantId;}
export interface BenchmarkDisplay{readonly id:string;readonly specificationId:SpecificationId;readonly priceEvidenceId:EvidenceId;readonly value:Money;readonly basis:Quantity;readonly place:string;readonly observedAt:string;readonly transactionLevel:'FARMGATE'|'WHOLESALE'|'RETAIL'|'MEMBER';readonly conditions:readonly string[];readonly methodVersion:string;readonly disclaimer:'REFERENCE_ONLY_NOT_FINAL_SAVINGS';}
export interface HistoricalOfferContext{readonly offer:MemberOffer;readonly benchmark:BenchmarkDisplay;readonly promise:FuturePricePromise;readonly specification:Specification;}
export interface CatalogPublicationContext{readonly actorId:ParticipantId;readonly grantIds:readonly AuthorityGrantId[];readonly at:string;}
export interface PriceObservationAttribution{readonly sourceId:string;readonly upstreamIdentity:string;}
export interface AttributedPriceObservation{readonly observation:PriceObservation;readonly recordedBy:ParticipantId;readonly authorityGrantId:AuthorityGrantId;readonly recordedAt:string;readonly sourceId:string;readonly upstreamIdentity:string;}
interface AuthorizedCatalogDecision{readonly grantId:AuthorityGrantId;readonly executionAt:string;}
const validTime=(value:string)=>{const n=Date.parse(value);if(Number.isNaN(n))throw new Error('TIME_INVALID');return n;};const requireText=(value:string,error:string)=>{if(!value.trim())throw new Error(error);};

export class GovernedPilotCatalogService{
 private readonly windows=new Map<string,SalesWindow>();private readonly observedPrices=new Map<EvidenceId,AttributedPriceObservation>();private readonly benchmarks=new Map<string,BenchmarkDisplay>();private readonly benchmarkByOffer=new Map<OfferId,string>();private readonly promiseByOffer=new Map<OfferId,FuturePricePromise>();
 constructor(private readonly authority:AuthorityEvaluator,private readonly catalog:InMemoryCatalog,private readonly clock:()=>string=()=>new Date().toISOString()){}
 private authorize(ctx:CatalogPublicationContext,action:string,targetId:string,quantity?:number):AuthorizedCatalogDecision{const executionAt=this.clock();validTime(executionAt);const request={actorId:ctx.actorId,action,targetId,at:executionAt,grantIds:ctx.grantIds,...(quantity===undefined?{}:{quantity})};const decision=this.authority.evaluate(request);if(!decision.allowed)throw new Error(`CATALOG_UNAUTHORIZED:${decision.reason}`);const grantId=decision.grantId;if(!grantId)throw new Error('CATALOG_UNAUTHORIZED:GRANT_ID_MISSING');return {grantId,executionAt};}
 publishSpecification(ctx:CatalogPublicationContext,spec:Specification){this.authorize(ctx,'catalog.specification.publish',String(spec.id));return this.catalog.publishSpecification(spec);}
 publishListing(ctx:CatalogPublicationContext,listing:CatalogListing){this.authorize(ctx,'catalog.listing.publish',listing.listingId);return this.catalog.publishListing(listing);}
 recordPriceObservation(ctx:CatalogPublicationContext,observation:PriceObservation,attribution:PriceObservationAttribution){requireText(attribution.sourceId,'PRICE_SOURCE_REQUIRED');requireText(attribution.upstreamIdentity,'PRICE_UPSTREAM_IDENTITY_REQUIRED');const auth=this.authorize(ctx,'catalog.price.observe',String(observation.specificationId));if(validTime(observation.observedAt)>validTime(auth.executionAt))throw new Error('PRICE_OBSERVATION_FUTURE');const recorded=this.catalog.recordPriceObservation(observation);const attributed:AttributedPriceObservation=Object.freeze({observation:recorded,recordedBy:ctx.actorId,authorityGrantId:auth.grantId,recordedAt:auth.executionAt,sourceId:attribution.sourceId,upstreamIdentity:attribution.upstreamIdentity});this.observedPrices.set(recorded.evidenceId,attributed);return attributed;}
 createSalesWindow(ctx:CatalogPublicationContext,input:SalesWindow){this.authorize(ctx,'catalog.sales-window.publish',input.id);if(this.windows.has(input.id))throw new Error('SALES_WINDOW_ID_DUPLICATE');const from=validTime(input.validFrom),until=validTime(input.validUntil);if(until<=from)throw new Error('SALES_WINDOW_TIME_INVALID');requireText(input.pickupPlace,'SALES_WINDOW_PLACE_REQUIRED');requireText(input.policyVersion,'SALES_WINDOW_POLICY_REQUIRED');if(input.createdBy!==ctx.actorId)throw new Error('SALES_WINDOW_ACTOR_MISMATCH');const frozen=Object.freeze({...input});this.windows.set(input.id,frozen);return frozen;}
 defineBenchmarkDisplay(ctx:CatalogPublicationContext,input:{id:string;specificationId:SpecificationId;priceEvidenceId:EvidenceId;methodVersion:string}){this.authorize(ctx,'catalog.benchmark.publish',input.id);if(this.benchmarks.has(input.id))throw new Error('BENCHMARK_DISPLAY_ID_DUPLICATE');const attributed=this.observedPrices.get(input.priceEvidenceId);if(!attributed)throw new Error('BENCHMARK_PRICE_EVIDENCE_UNKNOWN');const observation=attributed.observation;if(observation.specificationId!==input.specificationId)throw new Error('BENCHMARK_SPECIFICATION_MISMATCH');requireText(input.methodVersion,'BENCHMARK_METHOD_REQUIRED');const display:BenchmarkDisplay=Object.freeze({id:input.id,specificationId:input.specificationId,priceEvidenceId:input.priceEvidenceId,value:observation.price,basis:observation.basis,place:observation.place,observedAt:observation.observedAt,transactionLevel:observation.transactionLevel,conditions:Object.freeze([...observation.conditions]),methodVersion:input.methodVersion,disclaimer:'REFERENCE_ONLY_NOT_FINAL_SAVINGS'});this.benchmarks.set(input.id,display);return display;}
 publishOffer(ctx:CatalogPublicationContext,input:{offer:MemberOffer;salesWindowId:string;benchmarkDisplayId:string}){const auth=this.authorize(ctx,'catalog.offer.publish',String(input.offer.id),input.offer.quantity.amount);const window=this.windows.get(input.salesWindowId);if(!window||!window.active)throw new Error('SALES_WINDOW_INACTIVE');const benchmark=this.benchmarks.get(input.benchmarkDisplayId);if(!benchmark)throw new Error('BENCHMARK_DISPLAY_UNKNOWN');if(benchmark.specificationId!==input.offer.specificationId)throw new Error('OFFER_BENCHMARK_SPECIFICATION_MISMATCH');if(input.offer.pickupPlace!==window.pickupPlace)throw new Error('OFFER_WINDOW_PLACE_MISMATCH');if(validTime(input.offer.validFrom)<validTime(window.validFrom)||validTime(input.offer.validUntil)>validTime(window.validUntil))throw new Error('OFFER_OUTSIDE_SALES_WINDOW');if(!input.offer.priceEvidenceIds.includes(benchmark.priceEvidenceId))throw new Error('OFFER_BENCHMARK_EVIDENCE_NOT_RETAINED');if(input.offer.policyVersions.length===0)throw new Error('OFFER_POLICY_VERSION_REQUIRED');const promise=authorizePricePromise({id:`promise:${String(input.offer.id)}`,specificationId:input.offer.specificationId,quantity:input.offer.quantity,place:input.offer.pickupPlace,validFrom:input.offer.validFrom,validUntil:input.offer.validUntil,ruleVersion:input.offer.policyVersions[0]!,conditions:benchmark.conditions,authorityId:String(auth.grantId),evidenceIds:input.offer.priceEvidenceIds});const published=this.catalog.publishMemberOffer(input.offer);this.benchmarkByOffer.set(input.offer.id,input.benchmarkDisplayId);this.promiseByOffer.set(input.offer.id,promise);return published;}
 catalogView(input:{listingId:string;offerId:OfferId;benchmarkDisplayId:string;at:string}){const listing=this.catalog.getListing(input.listingId);if(!listing||!listing.active)throw new Error('LISTING_INACTIVE');const offer=this.catalog.getOffer(input.offerId);if(!offer||!this.catalog.isOfferExecutable(input.offerId,input.at))throw new Error('OFFER_NOT_EXECUTABLE');const publishedBenchmarkId=this.benchmarkByOffer.get(input.offerId);if(!publishedBenchmarkId||publishedBenchmarkId!==input.benchmarkDisplayId)throw new Error('CATALOG_VIEW_BENCHMARK_MISMATCH');const benchmark=this.benchmarks.get(input.benchmarkDisplayId);if(!benchmark)throw new Error('BENCHMARK_DISPLAY_UNKNOWN');if(listing.specificationId!==offer.specificationId||benchmark.specificationId!==offer.specificationId)throw new Error('CATALOG_VIEW_SPECIFICATION_MISMATCH');const listingSpec=this.catalog.getListingSpecification(input.listingId),offerSpec=this.catalog.getOfferSpecification(input.offerId);if(!listingSpec||!offerSpec||listingSpec.version!==offerSpec.version)throw new Error('CATALOG_VIEW_SPECIFICATION_VERSION_MISMATCH');const promise=this.promiseByOffer.get(input.offerId);if(!promise)throw new Error('CATALOG_VIEW_PRICE_PROMISE_MISSING');return Object.freeze({listing,offer,benchmark,promise,specification:offerSpec});}
 historicalOfferContext(offerId:OfferId,benchmarkDisplayId?:string):HistoricalOfferContext{const offer=this.catalog.getOffer(offerId);if(!offer)throw new Error('HISTORICAL_OFFER_UNKNOWN');const publishedBenchmarkId=this.benchmarkByOffer.get(offerId);if(!publishedBenchmarkId)throw new Error('HISTORICAL_OFFER_BENCHMARK_MISSING');if(benchmarkDisplayId!==undefined&&publishedBenchmarkId!==benchmarkDisplayId)throw new Error('HISTORICAL_OFFER_BENCHMARK_MISMATCH');const benchmark=this.benchmarks.get(publishedBenchmarkId);if(!benchmark||benchmark.specificationId!==offer.specificationId)throw new Error('HISTORICAL_OFFER_BENCHMARK_INVALID');const promise=this.promiseByOffer.get(offerId);if(!promise)throw new Error('HISTORICAL_OFFER_PRICE_PROMISE_MISSING');const specification=this.catalog.getOfferSpecification(offerId);if(!specification)throw new Error('HISTORICAL_OFFER_SPECIFICATION_MISSING');return Object.freeze({offer,benchmark,promise,specification});}
 benchmarkForOffer(offerId:OfferId):BenchmarkDisplay|undefined{const benchmarkId=this.benchmarkByOffer.get(offerId);return benchmarkId?this.benchmarks.get(benchmarkId):undefined;}
 catalogStore(){return this.catalog;}
 getAttributedPriceObservation(id:EvidenceId){return this.observedPrices.get(id);}
}
