import type {EvidenceId,Money,ParticipantId,Quantity,SpecificationId} from '../../kernel/src/index.js';

const validTime=(v:string)=>!Number.isNaN(Date.parse(v));
const positive=(q:Quantity)=>Number.isFinite(q.amount)&&q.amount>0;

export type SupplyFacet='CAPABILITY'|'CAPACITY'|'OFFER'|'AVAILABLE'|'OWNED_INVENTORY';
export interface SupplyFact{readonly id:string;readonly facet:SupplyFacet;readonly specificationId:SpecificationId;readonly quantity:Quantity;readonly place:string;readonly at:string;readonly evidenceIds:readonly EvidenceId[];}
export type SourcingMode='GROW'|'CONTRACT'|'BUY'|'PROCESS'|'IMPORT'|'ABSTAIN';
export interface SourcingAlternative{readonly mode:Exclude<SourcingMode,'ABSTAIN'>;readonly specificationId:SpecificationId;readonly quantity:Quantity;readonly place:string;readonly readyAt:string;readonly comparableCost:Money;readonly evidenceIds:readonly EvidenceId[];}
export interface SourcingDecision{readonly selected:SourcingMode;readonly compared:readonly SourcingAlternative[];readonly authorityId:string;readonly decidedAt:string;}

export class SupplyDecisionLedger{
 private facts=new Map<string,SupplyFact>();
 recordFact(input:SupplyFact){if(this.facts.has(input.id)||!positive(input.quantity)||!input.place.trim()||!validTime(input.at)||input.evidenceIds.length===0)throw new Error('SUPPLY_FACT_INVALID');const f=Object.freeze({...input,quantity:Object.freeze({...input.quantity}),evidenceIds:[...input.evidenceIds]});this.facts.set(input.id,f);return f;}
 decide(input:SourcingDecision){if(!input.authorityId.trim()||!validTime(input.decidedAt))throw new Error('SOURCING_AUTHORITY_REQUIRED');if(input.selected!=='ABSTAIN'&&input.compared.length===0)throw new Error('SOURCING_COMPARISON_REQUIRED');if(input.compared.length){const first=input.compared[0]!;for(const a of input.compared){if(a.specificationId!==first.specificationId||a.quantity.amount!==first.quantity.amount||a.quantity.unit!==first.quantity.unit||a.place!==first.place||a.readyAt!==first.readyAt||a.comparableCost.currency!==first.comparableCost.currency||a.evidenceIds.length===0)throw new Error('SOURCING_ALTERNATIVES_NOT_EQUIVALENT');}if(input.selected!=='ABSTAIN'&&!input.compared.some(a=>a.mode===input.selected))throw new Error('SOURCING_SELECTED_NOT_COMPARED');}return Object.freeze({...input,compared:[...input.compared]});}
}

export type TransformationKind='SPLIT'|'MERGE'|'REPACK'|'PROCESS'|'RETURN'|'MEASURED_VARIANCE';
export interface PhysicalTransform{readonly id:string;readonly kind:TransformationKind;readonly inputLotIds:readonly string[];readonly outputLotIds:readonly string[];readonly inputQuantity:Quantity;readonly outputQuantity:Quantity;readonly lossQuantity:Quantity;readonly occurredAt:string;readonly evidenceIds:readonly EvidenceId[];}
export interface ReturnedLot{readonly lotId:string;readonly parentLotId:string;readonly quantity:Quantity;readonly returnedAt:string;readonly returnEvidenceIds:readonly EvidenceId[];readonly qualityState?:'PENDING_INSPECTION'|'ACCEPTED'|'QUARANTINED'|'REJECTED';readonly qualityEvidenceIds?:readonly EvidenceId[];}

export class PhysicalLineageLedger{
 private transforms=new Map<string,PhysicalTransform>();private returns=new Map<string,ReturnedLot>();private lotCapacity=new Map<string,Quantity>();private consumedByLot=new Map<string,number>();
 registerLot(lotId:string,quantity:Quantity){if(this.lotCapacity.has(lotId)||!lotId.trim()||!positive(quantity))throw new Error('LINEAGE_LOT_INVALID');const q=Object.freeze({...quantity});this.lotCapacity.set(lotId,q);return q;}
 transform(input:PhysicalTransform){if(this.transforms.has(input.id)||input.inputLotIds.length===0||input.outputLotIds.length===0||input.evidenceIds.length===0||!validTime(input.occurredAt))throw new Error('TRANSFORMATION_EVIDENCE_REQUIRED');if(input.inputQuantity.unit!==input.outputQuantity.unit||input.inputQuantity.unit!==input.lossQuantity.unit||input.inputQuantity.amount<0||input.outputQuantity.amount<0||input.lossQuantity.amount<0)throw new Error('TRANSFORMATION_QUANTITY_INVALID');if(Math.abs(input.inputQuantity.amount-input.outputQuantity.amount-input.lossQuantity.amount)>1e-9)throw new Error('TRANSFORMATION_NOT_CONSERVED');if(new Set(input.inputLotIds).size!==input.inputLotIds.length||new Set(input.outputLotIds).size!==input.outputLotIds.length)throw new Error('TRANSFORMATION_LOT_DUPLICATE');if(input.inputLotIds.length!==1)throw new Error('TRANSFORMATION_INPUT_ALLOCATION_REQUIRED');const inputLotId=input.inputLotIds[0]!;const capacity=this.lotCapacity.get(inputLotId);if(!capacity||capacity.unit!==input.inputQuantity.unit)throw new Error('TRANSFORMATION_INPUT_LOT_UNKNOWN');const already=this.consumedByLot.get(inputLotId)??0;if(already+input.inputQuantity.amount>capacity.amount+1e-9)throw new Error('TRANSFORMATION_INPUT_OVERCONSUMED');for(const outputLotId of input.outputLotIds){if(this.lotCapacity.has(outputLotId))throw new Error('TRANSFORMATION_OUTPUT_LOT_DUPLICATE');}const perOutput=input.outputQuantity.amount/input.outputLotIds.length;this.consumedByLot.set(inputLotId,already+input.inputQuantity.amount);for(const outputLotId of input.outputLotIds)this.lotCapacity.set(outputLotId,Object.freeze({amount:perOutput,unit:input.outputQuantity.unit}));const t=Object.freeze({...input,inputLotIds:[...input.inputLotIds],outputLotIds:[...input.outputLotIds],evidenceIds:[...input.evidenceIds]});this.transforms.set(input.id,t);return t;}
 recordReturn(input:ReturnedLot){if(this.returns.has(input.lotId)||!positive(input.quantity)||!validTime(input.returnedAt)||input.returnEvidenceIds.length===0)throw new Error('RETURN_INVALID');const r=Object.freeze({...input,quantity:Object.freeze({...input.quantity}),returnEvidenceIds:[...input.returnEvidenceIds],...(input.qualityEvidenceIds?{qualityEvidenceIds:[...input.qualityEvidenceIds]}:{})});this.returns.set(input.lotId,r);return r;}
 availableReturn(lotId:string){const r=this.returns.get(lotId);if(!r)throw new Error('RETURN_UNKNOWN');if(r.qualityState!=='ACCEPTED'||!r.qualityEvidenceIds?.length)throw new Error('RETURN_QUALITY_DETERMINATION_REQUIRED');return r.quantity;}
}

export interface ReserveDesignation{readonly id:string;readonly lotId:string;readonly quantity:Quantity;readonly purpose:string;readonly minimumRetained:Quantity;readonly policyVersion:string;readonly designatedAt:string;readonly evidenceIds:readonly EvidenceId[];}
export interface ReserveRelease{readonly id:string;readonly reserveId:string;readonly quantity:Quantity;readonly authorityId:string;readonly memberObligations:readonly string[];readonly replacementOutlook:string;readonly postReleaseCoverage:Quantity;readonly releasedAt:string;readonly evidenceIds:readonly EvidenceId[];}
export class ReserveLedger{private reserves=new Map<string,ReserveDesignation>();private releases=new Map<string,ReserveRelease>();private releasedByReserve=new Map<string,number>();designate(r:ReserveDesignation){if(this.reserves.has(r.id)||!positive(r.quantity)||r.minimumRetained.unit!==r.quantity.unit||r.minimumRetained.amount<0||r.minimumRetained.amount>r.quantity.amount||!r.policyVersion.trim()||!r.purpose.trim()||r.evidenceIds.length===0||!validTime(r.designatedAt))throw new Error('RESERVE_INVALID');this.reserves.set(r.id,Object.freeze({...r}));return r;}release(x:ReserveRelease){const r=this.reserves.get(x.reserveId);if(this.releases.has(x.id)||!r||!positive(x.quantity)||x.quantity.unit!==r.quantity.unit||!x.authorityId.trim()||x.evidenceIds.length===0||!validTime(x.releasedAt))throw new Error('RESERVE_RELEASE_INVALID');const already=this.releasedByReserve.get(x.reserveId)??0;const remainingReleasable=r.quantity.amount-r.minimumRetained.amount-already;if(x.quantity.amount>remainingReleasable+1e-9)throw new Error('RESERVE_FLOOR_BREACH');if(x.postReleaseCoverage.unit!==r.quantity.unit||x.postReleaseCoverage.amount<r.minimumRetained.amount)throw new Error('RESERVE_COVERAGE_BREACH');const release=Object.freeze({...x,memberObligations:[...x.memberObligations],evidenceIds:[...x.evidenceIds]});this.releases.set(x.id,release);this.releasedByReserve.set(x.reserveId,already+x.quantity.amount);return release;}}

export interface FuturePricePromise{readonly id:string;readonly specificationId:SpecificationId;readonly quantity:Quantity;readonly place:string;readonly validFrom:string;readonly validUntil:string;readonly ruleVersion:string;readonly conditions:readonly string[];readonly authorityId:string;readonly evidenceIds:readonly EvidenceId[];}
export const authorizePricePromise=(p:FuturePricePromise)=>{if(!positive(p.quantity)||!p.place.trim()||!validTime(p.validFrom)||!validTime(p.validUntil)||Date.parse(p.validUntil)<=Date.parse(p.validFrom)||!p.ruleVersion.trim()||p.conditions.length===0||!p.authorityId.trim()||p.evidenceIds.length===0)throw new Error('PRICE_PROMISE_BOUNDARY_REQUIRED');return Object.freeze({...p,conditions:[...p.conditions],evidenceIds:[...p.evidenceIds]});};

export interface LiquidityPosition{readonly deployable:Money;readonly restricted:Money;readonly minimumHeadroom:Money;readonly nearestMaturityAt:string;}
export interface CapitalAction{readonly id:string;readonly cashOutlay:Money;readonly expectedReturn:Money;readonly lockUntil:string;readonly authorityId:string;readonly evidenceIds:readonly EvidenceId[];}
export const authorizeCapitalAction=(p:LiquidityPosition,a:CapitalAction)=>{if(p.deployable.currency!==a.cashOutlay.currency||p.minimumHeadroom.currency!==a.cashOutlay.currency||a.expectedReturn.currency!==a.cashOutlay.currency)throw new Error('CAPITAL_CURRENCY_MISMATCH');if(!validTime(p.nearestMaturityAt)||!validTime(a.lockUntil)||!a.authorityId.trim()||a.evidenceIds.length===0)throw new Error('CAPITAL_ACTION_INVALID');if(p.deployable.minor-a.cashOutlay.minor<p.minimumHeadroom.minor)throw new Error('LIQUIDITY_HARD_CONSTRAINT');if(Date.parse(a.lockUntil)>Date.parse(p.nearestMaturityAt)&&a.cashOutlay.minor>0n)throw new Error('MATURITY_CONSTRAINT');return Object.freeze({...a});};

export interface SecurityInterest{readonly id:string;readonly lotId:string;readonly claimantId:ParticipantId;readonly quantity:Quantity;readonly active:boolean;readonly authorityId:string;readonly evidenceIds:readonly EvidenceId[];}
export interface SecurityInterestRelease{readonly id:string;readonly securityInterestId:string;readonly releasedAt:string;readonly authorityId:string;readonly evidenceIds:readonly EvidenceId[];}
export class CollateralLedger{private claims=new Map<string,SecurityInterest>();private releases=new Map<string,SecurityInterestRelease>();pledge(c:SecurityInterest,lotQuantity:Quantity){if(this.claims.has(c.id))throw new Error('SECURITY_INTEREST_ID_DUPLICATE');if(!c.active||!positive(c.quantity)||c.quantity.unit!==lotQuantity.unit||!c.authorityId.trim()||c.evidenceIds.length===0)throw new Error('SECURITY_INTEREST_INVALID');const pledged=[...this.claims.values()].filter(x=>x.lotId===c.lotId&&x.active&&!this.releases.has(x.id)).reduce((n,x)=>n+x.quantity.amount,0);if(pledged+c.quantity.amount>lotQuantity.amount)throw new Error('DOUBLE_PLEDGE_REJECTED');const frozen=Object.freeze({...c,quantity:Object.freeze({...c.quantity}),evidenceIds:[...c.evidenceIds]});this.claims.set(c.id,frozen);return frozen;}release(x:SecurityInterestRelease){const claim=this.claims.get(x.securityInterestId);if(this.releases.has(x.securityInterestId)||!claim||!x.id.trim()||!x.authorityId.trim()||!validTime(x.releasedAt)||x.evidenceIds.length===0)throw new Error('SECURITY_INTEREST_RELEASE_INVALID');const frozen=Object.freeze({...x,evidenceIds:[...x.evidenceIds]});this.releases.set(x.securityInterestId,frozen);return frozen;}disposable(lotId:string,lotQuantity:Quantity){const enc=[...this.claims.values()].filter(x=>x.lotId===lotId&&x.active&&!this.releases.has(x.id)).reduce((n,x)=>n+x.quantity.amount,0);return Object.freeze({amount:lotQuantity.amount-enc,unit:lotQuantity.unit});}}

export type EpistemicKind='OBSERVATION'|'ASSERTION'|'INFERENCE'|'MODEL_OUTPUT';
export interface GovernedEvidence{readonly id:string;readonly kind:EpistemicKind;readonly statement:string;readonly sourceId:string;readonly upstreamIdentity:string;readonly observedAt:string;readonly evidenceIds:readonly EvidenceId[];}
export interface Contradiction{readonly id:string;readonly evidenceIds:readonly string[];readonly state:'OPEN'|'RESOLVED';readonly resolutionEvidenceIds:readonly EvidenceId[];}
export interface MaterialDecisionRecord{readonly id:string;readonly objective:string;readonly modelVersion:string;readonly inputs:Readonly<Record<string,string|number|boolean>>;readonly assumptions:readonly string[];readonly authorityId:string;readonly alternatives:readonly string[];readonly constraints:readonly string[];readonly decidedAt:string;readonly evidenceIds:readonly EvidenceId[];}
export class EvidenceGovernanceLedger{private evidence=new Map<string,GovernedEvidence>();private contradictions=new Map<string,Contradiction>();record(e:GovernedEvidence){if(this.evidence.has(e.id)||!e.statement.trim()||!e.sourceId.trim()||!e.upstreamIdentity.trim()||!validTime(e.observedAt)||e.evidenceIds.length===0)throw new Error('EVIDENCE_GOVERNANCE_INVALID');this.evidence.set(e.id,Object.freeze({...e,evidenceIds:[...e.evidenceIds]}));return e;}corroborationCount(ids:readonly string[]){const rows=ids.map(id=>this.evidence.get(id));if(rows.some(x=>!x))throw new Error('EVIDENCE_UNKNOWN');return new Set(rows.map(x=>x!.upstreamIdentity)).size;}contradict(c:Contradiction){if(c.evidenceIds.length<2||c.state==='OPEN'&&c.resolutionEvidenceIds.length>0||c.state==='RESOLVED'&&c.resolutionEvidenceIds.length===0)throw new Error('CONTRADICTION_INVALID');this.contradictions.set(c.id,Object.freeze({...c,evidenceIds:[...c.evidenceIds],resolutionEvidenceIds:[...c.resolutionEvidenceIds]}));return c;}decision(d:MaterialDecisionRecord){if(!d.objective.trim()||!d.modelVersion.trim()||Object.keys(d.inputs).length===0||d.assumptions.length===0||!d.authorityId.trim()||d.alternatives.length===0||d.constraints.length===0||!validTime(d.decidedAt)||d.evidenceIds.length===0)throw new Error('DECISION_RECONSTRUCTION_FIELDS_REQUIRED');return Object.freeze({...d,inputs:Object.freeze({...d.inputs}),assumptions:[...d.assumptions],alternatives:[...d.alternatives],constraints:[...d.constraints],evidenceIds:[...d.evidenceIds]});}}
