import test from 'node:test';import assert from 'node:assert/strict';
import {InMemoryMembershipBillingStore} from '../../dist/packages/membership/src/billing.js';import {InMemoryShoppingCreditStore} from '../../dist/packages/membership/src/credits.js';import {authorizeDemandCommitment,pooledDemandQuantity} from '../../dist/packages/catalog/src/commitment.js';import {authorizeOperatorAction,changeFeatureState} from '../../dist/packages/governance/src/operator-authority.js';
const now='2026-09-16T12:00:00Z',memberId='participant:a11-member';const offer={offerId:'offer:a11-rice',version:1,skuId:'sku:rice',state:'OPEN',validFrom:'2026-09-01T00:00:00Z',validUntil:'2026-10-01T00:00:00Z',policy:{minQuantity:5,maxQuantity:20,quantityStep:5}};const basket={basketId:'basket:a11',memberId,lines:[{offerId:offer.offerId,offerVersion:1,skuId:offer.skuId,quantity:10}]};const request={requestId:'request:a11',memberId,basketId:basket.basketId,offerId:offer.offerId,offerVersion:1,quantity:10};const owner={grantId:'grant:a11-owner',participantId:'owner:a11',role:'SYSTEM_OWNER',permissions:['feature:manage','operator:manage'],grantedAt:'2026-09-01T00:00:00Z',grantedBy:'system'};const warehouse={grantId:'grant:a11-warehouse',participantId:'operator:a11-warehouse',role:'WAREHOUSE_MANAGER',permissions:['business:read','warehouse:manage'],grantedAt:'2026-09-01T00:00:00Z',grantedBy:'owner:a11'};const eligible=s=>s==='ACTIVE'||s==='GRACE';function paymentEvidence(obligationId,amountMinor,providerReference){return {evidenceId:`evidence:${providerReference}`,providerReference,participantId:memberId,obligationId,amountMinor,verified:true,persisted:true,verifiedAt:now};}function commit(memberCommerceEligible=true,overrides={}){return authorizeDemandCommitment({request,basket,offer,memberCommerceEligible,now,...overrides});}
test('A11 grace-period membership remains commerce eligible',()=>{const billing=new InMemoryMembershipBillingStore();billing.issue({id:'invoice:a11',participantId:memberId,amountMinor:10000,issuedAt:'2026-09-01T00:00:00Z',dueAt:'2026-09-10T00:00:00Z'});billing.markDue('invoice:a11');billing.markPastDue('invoice:a11','2026-09-11T00:00:00Z');const standing=billing.standing(memberId,now);assert.equal(standing.state,'GRACE');const result=commit(eligible(standing.state));assert.equal(result.ok,true);assert.equal(pooledDemandQuantity([result.commitment],offer.offerId),10);});
test('A11 restricted membership cannot create pooled demand',()=>{const billing=new InMemoryMembershipBillingStore();billing.issue({id:'invoice:a11-r',participantId:memberId,amountMinor:10000,issuedAt:'2026-08-01T00:00:00Z',dueAt:'2026-08-10T00:00:00Z'});billing.markDue('invoice:a11-r');billing.markPastDue('invoice:a11-r','2026-08-11T00:00:00Z');const standing=billing.standing(memberId,now);assert.equal(standing.state,'RESTRICTED');assert.deepEqual(commit(eligible(standing.state)),{ok:false,code:'MEMBER_NOT_COMMERCE_ELIGIBLE'});});
test('A11 exact annual settlement restores ACTIVE standing',()=>{const billing=new InMemoryMembershipBillingStore();const id='invoice:a11-settle';billing.issue({id,participantId:memberId,amountMinor:10000,issuedAt:'2026-09-01T00:00:00Z',dueAt:'2026-09-10T00:00:00Z'});billing.markDue(id);billing.markPastDue(id,'2026-09-11T00:00:00Z');billing.recordAuthoritativeSettlement(id,paymentEvidence(id,10000,'settlement:a11'));assert.equal(billing.standing(memberId,now).state,'ACTIVE');});
test('A11 expired promotional credit contributes zero merchandise balance',()=>{const credits=new InMemoryShoppingCreditStore();credits.issuePromotionalCredit({id:'credit:a11-promo',participantId:memberId,amountMinor:2500,issuedAt:'2025-09-16T12:00:00Z',sourceReference:'promo:a11',campaignReference:'campaign:a11'});assert.equal(credits.balanceByApplicability(memberId,'MERCHANDISE',now),0);assert.equal(credits.get('credit:a11-promo').state,'EXPIRED');});
test('A11 shipping overpayment cannot become merchandise credit',()=>{const credits=new InMemoryShoppingCreditStore();const billing=new InMemoryMembershipBillingStore(credits);const id='invoice:a11-over';billing.issue({id,participantId:memberId,amountMinor:10000,issuedAt:'2026-09-01T00:00:00Z',dueAt:'2026-09-10T00:00:00Z'});billing.recordAuthoritativeSettlement(id,paymentEvidence(id,11000,'settlement:a11-over'));assert.equal(credits.balanceByApplicability(memberId,'MERCHANDISE'),0);assert.equal(credits.balanceByApplicability(memberId,'SHIPPING'),1000);});
test('A11 replayed commitment cannot double pooled demand',()=>{const first=commit();assert.equal(first.ok,true);const existing=new Map([[request.requestId,first.commitment]]);assert.deepEqual(commit(true,{existingByRequestId:existing}),first);assert.equal(pooledDemandQuantity([...existing.values()],offer.offerId),10);});
test('A11 stale offer cannot create pooled demand',()=>assert.deepEqual(commit(true,{request:{...request,offerVersion:0}}),{ok:false,code:'OFFER_VERSION_STALE'}));
test('A11 warehouse operator cannot acquire feature authority',()=>{assert.equal(authorizeOperatorAction({participantId:warehouse.participantId,permission:'feature:manage',grants:[warehouse],now}).allowed,false);assert.throws(()=>changeFeatureState({featureId:'catalog',state:'SUSPENDED',reason:'attack',actorId:warehouse.participantId,grants:[warehouse],now}),/FEATURE_CONTROL_UNAUTHORIZED/);});
test('A11 revoked warehouse authority fails closed immediately',()=>{const revoked={...warehouse,revokedAt:'2026-09-16T11:59:00Z'};assert.deepEqual(authorizeOperatorAction({participantId:warehouse.participantId,permission:'warehouse:manage',grants:[revoked],now}),{allowed:false,reason:'NO_ACTIVE_GRANT'});});
test('A11 owner feature mutation retains authoritative grant lineage',()=>{const event=changeFeatureState({featureId:'catalog',state:'SUSPENDED',reason:'controlled halt',actorId:owner.participantId,grants:[owner],now});assert.equal(event.changedBy,owner.participantId);assert.equal(event.authorityGrantId,owner.grantId);});
