import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const model=fs.readFileSync(new URL('../../packages/durability/sql/021_employee_membership_entitlement.sql',import.meta.url),'utf8');const bridge=fs.readFileSync(new URL('../../api/employee-membership-sync.js',import.meta.url),'utf8');const offboard=fs.readFileSync(new URL('../../api/employee-membership-end.js',import.meta.url),'utf8');
test('employment is authoritative and separate from operator authority',()=>{assert.match(model,/CREATE TABLE IF NOT EXISTS employee_employment/);assert.match(bridge,/employee_employment/);assert.doesNotMatch(bridge,/application_authority_grant/);assert.doesNotMatch(bridge,/employee_session/);});
test('employee free membership is one durable zero-fee entitlement model',()=>{assert.match(model,/employee_membership_entitlement/);assert.match(model,/annual_fee_minor bigint NOT NULL DEFAULT 0/);assert.match(model,/EMPLOYEE_SPONSORED/);});
test('legacy standing vocabulary is migrated before canonical constraint',()=>{assert.match(model,/standing='ACTIVE' WHERE standing='CURRENT'/);assert.match(model,/standing='GRACE' WHERE standing='PAST_DUE'/);assert.match(model,/standing='TERMINATED' WHERE standing='ENDED'/);});
test('sponsorship grant is atomic and preserves ordinary PRIMARY membership identity',()=>{assert.match(bridge,/WITH\s+new_membership AS/);assert.match(bridge,/WITH\s+sponsored_membership AS/);assert.match(bridge,/new_entitlement AS/);assert.match(bridge,/'PRIMARY','ACTIVE'/);assert.match(bridge,/HOUSEHOLD_MEMBERSHIP_REQUIRES_EXPLICIT_CONVERSION/);});
test('employment ending ends entitlement but not membership state',()=>{assert.match(offboard,/UPDATE\s+employee_membership_entitlement[\s\S]{0,240}?SET\s+state='ENDED'/);assert.match(offboard,/UPDATE\s+application_membership[\s\S]{0,240}?SET\s+member_type='PRIMARY',standing='INITIAL_FEE_DUE'/);assert.doesNotMatch(offboard,/UPDATE\s+application_membership[\s\S]{0,160}?SET\s+state='ENDED'/);});
test('offboarding is authorized, atomic and creates payable continuation',()=>{assert.match(offboard,/EMPLOYEE_MEMBERSHIP_END_REQUIRES_OWNER_OR_ADMIN/);assert.match(offboard,/WITH\s+ended_entitlement AS/);assert.match(offboard,/new_invoice AS/);assert.match(offboard,/ANNUAL_MEMBERSHIP_FEE_NOT_CONFIGURED/);});
test('operator authority remains an independent state machine',()=>{assert.doesNotMatch(offboard,/UPDATE application_authority_grant/);assert.doesNotMatch(bridge,/application_authority_grant/);});
