import test from 'node:test';import assert from 'node:assert/strict';import startHandler from '../../api/enrollment-verify-start.js';
function response(){const out={statusCode:null,body:null};return{out,setHeader(){},status(c){out.statusCode=c;return this},json(b){out.body=b;return this}}}
function baseSql({route='NEW',rateLimited=false,campaign=null}={}){const calls=[];const sql=async(strings,...values)=>{const text=strings.join('?');calls.push({text,values});
  if(text.includes('record_rate_limit_event'))return[{allowed:!rateLimited,current_count:1}];
  if(text.includes('FROM enrollment_campaign WHERE campaign_token'))return campaign?[{campaign_id:campaign}]:[];
  if(text.includes('resolve_enrollment_contact'))return[{route,application_id:'application:1',membership_id:route==='EXISTING_MEMBER'?'membership:existing':null}];
  if(text.includes('create_member_auth_challenge'))return[{challenge_id:'challenge:1'}];
  if(text.includes('create_enrollment_verification_challenge'))return[{challenge_id:'enrollment-challenge:1'}];
  throw new Error('UNEXPECTED_QUERY: '+text)};sql.calls=calls;return sql}
const valid={fullName:'Ama Mensah',governmentEmployer:'Ghana Health Service',phone:'0240000000',channel:'PHONE'};
const opts=(sql,extra={})=>({env:{VERCEL_ENV:'preview'},sql,code:123456,deliverChallenge:async()=>{},now:Date.parse('2026-09-22T00:00:00Z'),...extra});

test('rejects non-POST',async()=>{const r=response();await startHandler({method:'GET'},r,{});assert.equal(r.out.statusCode,405)});
test('full name required',async()=>{const r=response();await startHandler({method:'POST',body:{governmentEmployer:'GHS',phone:'0240000000'}},r,opts(baseSql()));assert.equal(r.out.body.error,'FULL_NAME_REQUIRED')});
test('email verification channel unavailable',async()=>{const r=response();await startHandler({method:'POST',body:{...valid,channel:'EMAIL'}},r,opts(baseSql()));assert.equal(r.out.statusCode,409);assert.equal(r.out.body.error,'VERIFICATION_CHANNEL_UNAVAILABLE')});
test('malformed phone rejected before any database access',async()=>{const sql=baseSql(),r=response();await startHandler({method:'POST',body:{...valid,phone:'123'}},r,opts(sql));assert.equal(r.out.statusCode,400);assert.equal(r.out.body.error,'SMS_RECIPIENT_INVALID');assert.equal(sql.calls.length,0)});
test('invalid campaign token rejected',async()=>{const sql=baseSql({campaign:null}),r=response();await startHandler({method:'POST',body:{...valid,campaignToken:'bad-token'}},r,opts(sql));assert.equal(r.out.body.error,'CAMPAIGN_TOKEN_INVALID')});
test('new enrollment issues an enrollment-prefixed challenge and a generic response',async()=>{const sql=baseSql({route:'NEW'}),r=response();await startHandler({method:'POST',body:valid},r,opts(sql));assert.equal(r.out.statusCode,200);assert.equal(r.out.body.ok,true);assert.match(r.out.body.challengeId,/^enrollment-challenge:/);assert.match(sql.calls.find(c=>c.text.includes('resolve_enrollment_contact')).text,/resolve_enrollment_contact/)});
test('existing member routes to the member sign-in challenge with the same generic response shape',async()=>{const sql=baseSql({route:'EXISTING_MEMBER'}),r=response();await startHandler({method:'POST',body:valid},r,opts(sql));assert.equal(r.out.statusCode,200);assert.equal(r.out.body.ok,true);assert.match(r.out.body.challengeId,/^challenge:/);assert.equal(r.out.body.message,'If these details are eligible for enrollment, a verification code has been sent.')});
test('resumed pending application reissues an enrollment challenge, not a new membership',async()=>{const sql=baseSql({route:'RESUME_PENDING'}),r=response();await startHandler({method:'POST',body:valid},r,opts(sql));assert.equal(r.out.statusCode,200);assert.match(r.out.body.challengeId,/^enrollment-challenge:/)});
test('rate-limited request returns the identical generic response without querying resolution',async()=>{const sql=baseSql({rateLimited:true}),r=response();await startHandler({method:'POST',body:valid},r,opts(sql));assert.equal(r.out.statusCode,200);assert.equal(r.out.body.message,'If these details are eligible for enrollment, a verification code has been sent.');assert.equal(r.out.body.challengeId,undefined);assert.equal(sql.calls.some(c=>c.text.includes('resolve_enrollment_contact')),false)});
test('delivery failure still returns the generic response, not a distinguishable error',async()=>{const sql=baseSql({route:'NEW'}),r=response();await startHandler({method:'POST',body:valid},r,opts(sql,{deliverChallenge:async()=>{throw Object.assign(new Error('down'),{code:'SMS_PROVIDER_DELIVERY_FAILED'})}}));assert.equal(r.out.statusCode,200);assert.equal(r.out.body.challengeId,undefined)});
