import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const read=p=>fs.readFileSync(new URL(`../../${p}`,import.meta.url),'utf8');
const schema=read('packages/durability/sql/021_j16_j17_j20_launch_journeys.sql'),commit=read('api/commit-sandbox.js'),tiers=read('lib/operator-tiers.js'),issue=read('api/fulfillment-release-code.js'),redeem=read('api/fulfillment-release-redeem.js'),catalog=read('api/catalog-offers.js');
test('J16 offer schema carries MOQ maximum and campaign capacity',()=>{assert.match(schema,/min_order_quantity/);assert.match(schema,/max_order_quantity/);assert.match(schema,/campaign_capacity/);assert.match(schema,/order_range_check/);});
test('J16 commitment serializes on offer and enforces all quantity bounds',()=>{assert.match(commit,/FOR UPDATE/);assert.match(commit,/unit_quantity>=o\.min_order_quantity/);assert.match(commit,/unit_quantity<=o\.max_order_quantity/);assert.match(commit,/sum\(c\.quantity\)/);assert.match(commit,/campaign_capacity/);});
test('J17 release authority is bounded, hashed, expiring and single-use',()=>{assert.match(schema,/code_hash text NOT NULL UNIQUE/);assert.match(schema,/one_active_per_fulfillment/);assert.match(issue,/createHash\('sha256'\)/);assert.match(issue,/24\*60\*60\*1000/);assert.match(redeem,/state='ACTIVE' AND expires_at>now\(\)/);assert.match(redeem,/state='REDEEMED'/);});
test('J17 issue requires member ownership and redemption requires explicit release scope',()=>{assert.match(issue,/member:orders\.read/);assert.match(issue,/c\.participant_id=/);assert.match(redeem,/operator:release\.manage/);});
test('J19 limited tiers do not receive catalog or release authority',()=>{assert.match(tiers,/OPERATOR_RELEASE_SCOPE/);assert.match(tiers,/OPERATOR_CATALOG_SCOPE/);const fulfillment=tiers.match(/\[OPERATOR_FULFILLMENT_ACTOR_ID\]: \[([^\]]+)\]/)?.[1]||'';const finance=tiers.match(/\[OPERATOR_FINANCE_ACTOR_ID\]: \[([^\]]+)\]/)?.[1]||'';assert.doesNotMatch(fulfillment,/release|catalog/);assert.doesNotMatch(finance,/release|catalog/);});
test('J20 catalog mutations require explicit catalog authority and delete closes rather than destroys',()=>{assert.match(catalog,/operator:catalog\.manage/);assert.match(catalog,/CATALOG_CAPABLE_OPERATORS/);assert.match(catalog,/UPDATE preview_member_offer SET status='CLOSED'/);assert.doesNotMatch(catalog,/DELETE FROM preview_member_offer/);});
