import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';const read=p=>fs.readFileSync(new URL('../../'+p,import.meta.url),'utf8');const api=read('api/catalog-admin.js'),schema=read('packages/durability/sql/027_catalog_administration_v1.sql'),ui=read('public/catalog-admin.html'),client=read('public/catalog-admin.js'),bridge=read('public/governed-fetch-extension.js'),pg=read('scripts/test-postgres-durability.sh');
test('J20 catalog admin is governed by explicit catalog authority',()=>{assert.match(api,/operator:catalog\.manage/);assert.match(api,/CATALOG_CAPABLE_OPERATORS/);assert.match(bridge,/\/api\/catalog-admin/);});
test('J20 uses Neon tagged templates rather than unsupported query-array invocation',()=>{assert.match(api,/await sql`SELECT/);assert.doesNotMatch(api,/sql\(['"]/);});
test('J20 durable catalog versions specifications, categories and unique SKUs',()=>{assert.match(schema,/CREATE TABLE IF NOT EXISTS catalog_category/);assert.match(schema,/PRIMARY KEY\(specification_id,version\)/);assert.match(schema,/sku text NOT NULL UNIQUE/);assert.match(schema,/REFERENCES catalog_category/);assert.match(schema,/one_active_version/);});
test('J20 publication is one data-modifying CTE statement with guarded supersession',()=>{assert.match(api,/candidate AS MATERIALIZED/);assert.match(api,/deactivated AS \(UPDATE catalog_specification/);assert.match(api,/spec AS \(INSERT INTO catalog_specification/);assert.match(api,/listing AS \(INSERT INTO catalog_listing/);assert.match(api,/SPECIFICATION_VERSION_NOT_ADVANCED/);assert.match(api,/ON CONFLICT\(listing_id\) DO UPDATE/);});
test('J20 supports edit, deactivate and reactivate without destructive deletes',()=>{assert.match(api,/\['GET','POST','PATCH','DELETE'\]/);assert.match(api,/SET active=false/);assert.match(api,/REACTIVATE/);assert.doesNotMatch(api,/DELETE FROM catalog_/);});
test('J20 mutations carry durable actor audit lineage',()=>{assert.match(schema,/CREATE TABLE IF NOT EXISTS catalog_audit_event/);assert.match(schema,/before_state jsonb/);assert.match(schema,/after_state jsonb/);assert.match(api,/catalog_audit_event/);});
test('J20 operator UI covers category publication and listing edit lifecycle after authority probe',()=>{assert.match(ui,/category-form/);assert.match(ui,/catalog-form/);assert.match(client,/form\.hidden=!allowed/);assert.match(client,/data-edit/);assert.match(client,/data-toggle/);assert.match(client,/data-category/);});
test('J20 PostgreSQL harness proves stale-version safety and rollback on duplicate SKU',()=>{assert.match(pg,/027_catalog_administration_v1\.sql/);assert.match(pg,/stale publication damaged active specification/);assert.match(pg,/failed publication leaked partial state/);assert.match(pg,/duplicate SKU unexpectedly succeeded/);assert.match(pg,/specification revision did not preserve listing identity/);assert.match(pg,/concurrent publication violated active-version or referential invariant/);});
