import test from 'node:test'; import assert from 'node:assert/strict';
import {quantity,subtractQuantity,asId} from '../../dist/packages/kernel/src/index.js';
import {InMemoryAuthorityStore,InMemoryConstraintStore,AuthorityEvaluator} from '../../dist/packages/authority/src/index.js';
import {CommandBus,InMemoryIdempotencyStore,InMemoryVersionStore,InMemoryRejectionEvidenceSink} from '../../dist/packages/application/src/index.js';
import {EvidenceLedger} from '../../dist/packages/evidence/src/index.js';
const pid=(x)=>asId(x), gid=(x)=>asId(x), cid=(x)=>asId(x), eid=(x)=>asId(x), xid=(x)=>asId(x);

const baseCommand=(overrides={})=>({commandId:cid('command:base'),idempotencyKey:'idem:base',actorId:pid('participant:operator'),action:'RecordPriceEvidence',authorityGrantIds:[],evidenceIds:[],policyVersions:['policy:v1'],requestedAt:'2026-09-06T20:00:00Z',correlationId:'corr:base',payload:{},...overrides});

test('INV-007 physical quantity cannot go negative',()=>{ assert.throws(()=>subtractQuantity(quantity(4,'kg'),quantity(5,'kg')),/NEGATIVE_PHYSICAL_TRUTH/); assert.deepEqual(subtractQuantity(quantity(5,'kg'),quantity(4,'kg')),quantity(1,'kg')); });
test('INV-001 authority requires a current scoped grant',()=>{ const s=new InMemoryAuthorityStore(); const ev=new AuthorityEvaluator(s); const actor=pid('participant:operator'); assert.equal(ev.evaluate({actorId:actor,action:'AllocateLotQuantity',targetId:'lot:1',at:'2026-09-06T20:00:00Z',grantIds:[]}).allowed,false); s.put({id:gid('grant:1'),grantorId:pid('participant:board'),actorId:actor,actions:['AllocateLotQuantity'],targetPrefix:'lot:',validFrom:'2026-09-01T00:00:00Z'}); assert.equal(ev.evaluate({actorId:actor,action:'AllocateLotQuantity',targetId:'lot:1',at:'2026-09-06T20:00:00Z',grantIds:[gid('grant:1')]}).allowed,true); });
test('FX-020 revoked authority is rejected at execution time',()=>{ const s=new InMemoryAuthorityStore(); const ev=new AuthorityEvaluator(s); const actor=pid('participant:operator'); const id=gid('grant:2'); s.put({id,grantorId:pid('participant:board'),actorId:actor,actions:['RecordPickupPerformance'],validFrom:'2026-09-01T00:00:00Z'}); s.revoke(id,'2026-09-06T19:00:00Z'); assert.equal(ev.evaluate({actorId:actor,action:'RecordPickupPerformance',at:'2026-09-06T20:00:00Z',grantIds:[id]}).reason,'REVOKED'); });
test('INV-027 idempotency survives command-bus recreation when store is shared',async()=>{ const s=new InMemoryAuthorityStore(); const actor=pid('participant:operator'); const g=gid('grant:3'); s.put({id:g,grantorId:pid('participant:board'),actorId:actor,actions:['RecordPriceEvidence'],validFrom:'2026-09-01T00:00:00Z'}); const idem=new InMemoryIdempotencyStore(); let effects=0; const h={action:'RecordPriceEvidence',handle:()=>{effects++;return ['event:1'];}}; const bus1=new CommandBus(new AuthorityEvaluator(s),{idempotencyStore:idem}); bus1.register(h); const cmd=baseCommand({commandId:cid('command:1'),idempotencyKey:'idem:1',actorId:actor,authorityGrantIds:[g]}); const a=await bus1.execute(cmd); const bus2=new CommandBus(new AuthorityEvaluator(s),{idempotencyStore:idem}); bus2.register(h); const b=await bus2.execute(cmd); assert.equal(a.status,'ACCEPTED'); assert.equal(b.replayed,true); assert.equal(effects,1); });
test('INV-024 correction preserves original evidence and lineage',()=>{ const l=new EvidenceLedger(); const e1={id:eid('evidence:1'),kind:'MEASUREMENT',source:'scale:1',observedAt:'2026-09-06T18:00:00Z',recordedAt:'2026-09-06T18:01:00Z',scope:'lot:1 mass',grade:'E1',payload:{kg:20}}; const e2={...e1,id:eid('evidence:2'),recordedAt:'2026-09-06T18:10:00Z',payload:{kg:19.8},supersedes:e1.id}; l.appendEvidence(e1);l.appendEvidence(e2); assert.equal(l.getEvidence(e1.id).payload.kg,20); assert.equal(l.getEvidence(e2.id).payload.kg,19.8); assert.deepEqual(l.lineageEdges()[0],{fromId:e1.id,toId:e2.id,kind:'CORRECTS'}); });

test('INV-001 delegated authority cannot exceed parent scope',()=>{ const s=new InMemoryAuthorityStore(); const board=pid('participant:board'), supervisor=pid('participant:supervisor'), agent=pid('participant:agent'); const parent=gid('grant:parent'); s.put({id:parent,grantorId:board,actorId:supervisor,actions:['RecordPriceEvidence'],targetPrefix:'commodity:',validFrom:'2026-09-01T00:00:00Z',validUntil:'2026-09-30T00:00:00Z',maxQuantity:100}); assert.throws(()=>s.put({id:gid('grant:bad-child'),parentGrantId:parent,grantorId:supervisor,actorId:agent,actions:['RecordPriceEvidence','AllocateLotQuantity'],targetPrefix:'commodity:',validFrom:'2026-09-01T00:00:00Z',validUntil:'2026-09-30T00:00:00Z',maxQuantity:100}),/DELEGATION_ACTION_ESCALATION/); s.put({id:gid('grant:child'),parentGrantId:parent,grantorId:supervisor,actorId:agent,actions:['RecordPriceEvidence'],targetPrefix:'commodity:rice:',validFrom:'2026-09-02T00:00:00Z',validUntil:'2026-09-20T00:00:00Z',maxQuantity:20}); assert.equal(new AuthorityEvaluator(s).evaluate({actorId:agent,action:'RecordPriceEvidence',targetId:'commodity:rice:accra',quantity:10,at:'2026-09-06T20:00:00Z',grantIds:[gid('grant:child')]}).allowed,true); });

test('INV-001 parent revocation invalidates delegated child at execution',()=>{ const s=new InMemoryAuthorityStore(); const board=pid('participant:board'), supervisor=pid('participant:supervisor'), agent=pid('participant:agent'); const parent=gid('grant:p2'), child=gid('grant:c2'); s.put({id:parent,grantorId:board,actorId:supervisor,actions:['RecordPriceEvidence'],validFrom:'2026-09-01T00:00:00Z'}); s.put({id:child,parentGrantId:parent,grantorId:supervisor,actorId:agent,actions:['RecordPriceEvidence'],validFrom:'2026-09-01T00:00:00Z'}); s.revoke(parent,'2026-09-06T19:00:00Z'); assert.equal(new AuthorityEvaluator(s).evaluate({actorId:agent,action:'RecordPriceEvidence',at:'2026-09-06T20:00:00Z',grantIds:[child]}).reason,'DELEGATION_INVALID'); });

test('INV-001 stop and hold constraints outrank otherwise valid grants',()=>{ const s=new InMemoryAuthorityStore(), c=new InMemoryConstraintStore(); const actor=pid('participant:operator'), g=gid('grant:hold'); s.put({id:g,grantorId:pid('participant:board'),actorId:actor,actions:['AllocateLotQuantity'],targetPrefix:'lot:',validFrom:'2026-09-01T00:00:00Z'}); c.put({id:xid('constraint:stop'),kind:'STOP',reason:'safety recall',action:'AllocateLotQuantity',targetPrefix:'lot:recalled:',activeFrom:'2026-09-06T18:00:00Z'}); const ev=new AuthorityEvaluator(s,c); assert.equal(ev.evaluate({actorId:actor,action:'AllocateLotQuantity',targetId:'lot:recalled:1',at:'2026-09-06T20:00:00Z',grantIds:[g]}).reason,'STOP_ACTIVE'); assert.equal(ev.evaluate({actorId:actor,action:'AllocateLotQuantity',targetId:'lot:normal:1',at:'2026-09-06T20:00:00Z',grantIds:[g]}).reason,'ALLOWED'); });

test('INV-028 expectedVersion rejects stale consequential command',async()=>{ const s=new InMemoryAuthorityStore(); const actor=pid('participant:operator'), g=gid('grant:version'); s.put({id:g,grantorId:pid('participant:board'),actorId:actor,actions:['AllocateLotQuantity'],targetPrefix:'lot:',validFrom:'2026-09-01T00:00:00Z'}); const versions=new InMemoryVersionStore(); versions.set('lot:1',4); const bus=new CommandBus(new AuthorityEvaluator(s),{versionStore:versions}); bus.register({action:'AllocateLotQuantity',handle:()=>['event:allocation']}); const r=await bus.execute(baseCommand({commandId:cid('command:stale'),idempotencyKey:'idem:stale',actorId:actor,action:'AllocateLotQuantity',targetId:'lot:1',expectedVersion:3,authorityGrantIds:[g]})); assert.equal(r.status,'REJECTED'); assert.equal(r.reason,'VERSION_CONFLICT'); });

test('C10 rejected material commands produce attributable evidence',async()=>{ const s=new InMemoryAuthorityStore(); const sink=new InMemoryRejectionEvidenceSink(); const bus=new CommandBus(new AuthorityEvaluator(s),{rejectionEvidence:sink}); const r=await bus.execute(baseCommand({commandId:cid('command:rejected'),idempotencyKey:'idem:rejected'})); assert.equal(r.reason,'NO_GRANT'); assert.equal(sink.all().length,1); assert.equal(sink.all()[0].actorId,'participant:operator'); assert.equal(sink.all()[0].correlationId,'corr:base'); });

test('FX-019 AI/service actor cannot execute outside explicit delegated authority',async()=>{ const s=new InMemoryAuthorityStore(); const ai=pid('participant:ai-agent'), board=pid('participant:board'), g=gid('grant:ai'); s.put({id:g,grantorId:board,actorId:ai,actions:['RecordPriceEvidence'],targetPrefix:'commodity:',validFrom:'2026-09-01T00:00:00Z'}); const bus=new CommandBus(new AuthorityEvaluator(s)); bus.register({action:'AllocateLotQuantity',handle:()=>['event:bad']}); const r=await bus.execute(baseCommand({commandId:cid('command:ai'),idempotencyKey:'idem:ai',actorId:ai,action:'AllocateLotQuantity',targetId:'lot:1',authorityGrantIds:[g]})); assert.equal(r.status,'REJECTED'); assert.equal(r.reason,'ACTION_OUT_OF_SCOPE'); });
