import test from 'node:test'; import assert from 'node:assert/strict';
import {quantity,subtractQuantity,asId} from '../../dist/packages/kernel/src/index.js';
import {InMemoryAuthorityStore,AuthorityEvaluator} from '../../dist/packages/authority/src/index.js';
import {CommandBus} from '../../dist/packages/application/src/index.js';
import {EvidenceLedger} from '../../dist/packages/evidence/src/index.js';
const pid=(x)=>asId(x), gid=(x)=>asId(x), cid=(x)=>asId(x), eid=(x)=>asId(x);

test('INV-007 physical quantity cannot go negative',()=>{ assert.throws(()=>subtractQuantity(quantity(4,'kg'),quantity(5,'kg')),/NEGATIVE_PHYSICAL_TRUTH/); assert.deepEqual(subtractQuantity(quantity(5,'kg'),quantity(4,'kg')),quantity(1,'kg')); });
test('INV-001 authority requires a current scoped grant',()=>{ const s=new InMemoryAuthorityStore(); const ev=new AuthorityEvaluator(s); const actor=pid('participant:operator'); assert.equal(ev.evaluate({actorId:actor,action:'AllocateLotQuantity',targetId:'lot:1',at:'2026-09-06T20:00:00Z',grantIds:[]}).allowed,false); s.put({id:gid('grant:1'),grantorId:pid('participant:board'),actorId:actor,actions:['AllocateLotQuantity'],targetPrefix:'lot:',validFrom:'2026-09-01T00:00:00Z'}); assert.equal(ev.evaluate({actorId:actor,action:'AllocateLotQuantity',targetId:'lot:1',at:'2026-09-06T20:00:00Z',grantIds:[gid('grant:1')]}).allowed,true); });
test('FX-020 revoked authority is rejected at execution time',()=>{ const s=new InMemoryAuthorityStore(); const ev=new AuthorityEvaluator(s); const actor=pid('participant:operator'); const id=gid('grant:2'); s.put({id,grantorId:pid('participant:board'),actorId:actor,actions:['RecordPickupPerformance'],validFrom:'2026-09-01T00:00:00Z'}); s.revoke(id,'2026-09-06T19:00:00Z'); assert.equal(ev.evaluate({actorId:actor,action:'RecordPickupPerformance',at:'2026-09-06T20:00:00Z',grantIds:[id]}).reason,'REVOKED'); });
test('INV-027 duplicate command is effect-idempotent',async()=>{ const s=new InMemoryAuthorityStore(); const actor=pid('participant:operator'); const g=gid('grant:3'); s.put({id:g,grantorId:pid('participant:board'),actorId:actor,actions:['RecordPriceEvidence'],validFrom:'2026-09-01T00:00:00Z'}); const bus=new CommandBus(new AuthorityEvaluator(s)); let effects=0; bus.register({action:'RecordPriceEvidence',handle:()=>{effects++;return ['event:1'];}}); const cmd={commandId:cid('command:1'),idempotencyKey:'idem:1',actorId:actor,action:'RecordPriceEvidence',authorityGrantIds:[g],evidenceIds:[],policyVersions:['pricing:v1'],requestedAt:'2026-09-06T20:00:00Z',correlationId:'corr:1',payload:{}}; const a=await bus.execute(cmd), b=await bus.execute(cmd); assert.equal(a.status,'ACCEPTED'); assert.equal(b.replayed,true); assert.equal(effects,1); });
test('INV-024 correction preserves original evidence and lineage',()=>{ const l=new EvidenceLedger(); const e1={id:eid('evidence:1'),kind:'MEASUREMENT',source:'scale:1',observedAt:'2026-09-06T18:00:00Z',recordedAt:'2026-09-06T18:01:00Z',scope:'lot:1 mass',grade:'E1',payload:{kg:20}}; const e2={...e1,id:eid('evidence:2'),recordedAt:'2026-09-06T18:10:00Z',payload:{kg:19.8},supersedes:e1.id}; l.appendEvidence(e1);l.appendEvidence(e2); assert.equal(l.getEvidence(e1.id).payload.kg,20); assert.equal(l.getEvidence(e2.id).payload.kg,19.8); assert.deepEqual(l.lineageEdges()[0],{fromId:e1.id,toId:e2.id,kind:'CORRECTS'}); });
