import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
const migration=fs.readFileSync(new URL('../../packages/durability/sql/031_member_auth_challenge_atomicity.sql',import.meta.url),'utf8');
const challenge=fs.readFileSync(new URL('../../api/member-auth-challenge.js',import.meta.url),'utf8');
const verify=fs.readFileSync(new URL('../../api/member-auth-verify.js',import.meta.url),'utf8');
const durability=fs.readFileSync(new URL('../../scripts/test-postgres-durability.sh',import.meta.url),'utf8');
test('native auth issuance is serialized and capped in PostgreSQL',()=>{assert.match(migration,/create_member_auth_challenge/);assert.match(migration,/pg_advisory_xact_lock/);assert.match(migration,/15 minutes/);assert.match(migration,/>= 5/);assert.match(challenge,/create_member_auth_challenge/);assert.doesNotMatch(challenge,/SELECT count\(\*\)/);});
test('native auth verification and session creation are one database statement',()=>{assert.match(migration,/verify_member_auth_challenge/);assert.match(migration,/attempts\+1>=5/);assert.match(migration,/INSERT INTO member_session/);assert.match(migration,/state='OPEN'/);assert.match(verify,/verify_member_auth_challenge/);assert.doesNotMatch(verify,/UPDATE member_auth_challenge/);});
test('native auth migration fails closed on historical inconsistencies',()=>{assert.match(migration,/attempts outside the certified 0\.\.5 range/);assert.match(migration,/inconsistent USED\/used_at state/);assert.match(migration,/attempts BETWEEN 0 AND 5/);assert.match(migration,/\(state='USED'\)=\(used_at IS NOT NULL\)/);});
test('durability campaign includes native auth concurrency attacks',()=>{assert.match(durability,/concurrent member-auth issuance exceeded five challenges/);assert.match(durability,/concurrent correct member-auth verification was not single-use/);assert.match(durability,/concurrent wrong member-auth attempts escaped the five-attempt cap/);assert.match(durability,/correct versus fifth-wrong member-auth race produced an impossible result/);});
