import test from 'node:test';
import assert from 'node:assert/strict';
import handler from '../../api/membership-subscription-settle.js';
const NOW=Date.parse('2026-09-18T12:00:00Z'),ENV={PRODUCTION_APPLICATION_ACCESS_ENABLED:'true'};
function req(body={},authorized=true){return{method:'POST',headers:{'x-request-id':'req:settle',...(authorized?{'x-membership-settlement-authority':'test-authority'}:{})},body};}
function res(){const r={statusCode:null,body:null,headers:{}};return{r,setHeader(k,v){r.headers[k]=v;},status(c){r.statusCode=c;return this;},json(b){r.body=b;return this;}};}
function sqlFixture({invoiceState='OPEN',evidence=null,membershipState='INACTIVE',standing=null,atomicWins=true,atomicError=false,memberType='PRIMARY',publicMemberId='WFC-P-PREISSUED'}={}){const calls=[];const sql=async(strings,...values)=>{const text=strings.join('?');calls.push({text,values});if(text.includes('FROM membership_subscription_invoice i JOIN application_membership'))return[{invoice_id:'invoice:1',membership_id:'membership:1',state:invoiceState,settlement_evidence_id:evidence,participant_id:'participant:member',membership_state:membershipState,standing:standing??(membershipState==='ACTIVE'?'ACTIVE':'INITIAL_FEE_DUE'),member_type:memberType,public_member_id:publicMemberId}];if(text.includes('WITH settled_invoice')){if(atomicError){const error=new Error('division by zero');error.code='22012';throw error;}return atomicWins?[{membership_id:'membership:1',public_member_id:publicMemberId,ok:1}]:[];}throw new Error(`UNEXPECTED_QUERY ${text}`);};sql.calls=calls;return sql;}
async function invoke(sql,body={invoiceId:'invoice:1',settlementEvidenceId:'evidence:pay:1'},authorized=true){const out=res();await handler(req(body,authorized),out,{sql,env:ENV,now:NOW,authorizeSettlement:()=>authorized});return out.r;}
test.beforeEach(()=>{process.env.VERCEL_ENV='production';});
test('trusted settlement activates already-numbered membership without changing member number',async()=>{const sql=sqlFixture(),r=await invoke(sql);assert.equal(r.statusCode,200);assert.equal(r.body.membershipState,'ACTIVE');assert.equal(r.body.publicMemberId,'WFC-P-PREISSUED');assert.equal(r.body.loginIdentityBound,false);const atomic=sql.calls.find(c=>c.text.includes('WITH settled_invoice'));assert.ok(atomic);assert.doesNotMatch(atomic.text,/COALESCE\(m\.public_member_id/);assert.doesNotMatch(atomic.text,/application_identity_binding/);assert.match(atomic.text,/INSERT INTO application_access_audit/);});
test('settlement fails closed when enrollment did not issue member number',async()=>{const r=await invoke(sqlFixture({publicMemberId:null}));assert.equal(r.statusCode,409);assert.equal(r.body.error,'MEMBER_NUMBER_NOT_ISSUED');});
test('untrusted caller cannot assert settlement evidence',async()=>{const r=await invoke(sqlFixture(),undefined,false);assert.equal(r.statusCode,401);assert.equal(r.body.error,'SETTLEMENT_AUTHORITY_REQUIRED');});
test('same evidence replay is idempotent',async()=>{const sql=sqlFixture({invoiceState:'PAID',evidence:'evidence:pay:1',membershipState:'ACTIVE'}),r=await invoke(sql);assert.equal(r.statusCode,200);assert.equal(r.body.idempotent,true);assert.equal(sql.calls.some(c=>c.text.includes('WITH settled_invoice')),false);});
test('different evidence cannot replay paid invoice',async()=>{const r=await invoke(sqlFixture({invoiceState:'PAID',evidence:'evidence:other',membershipState:'ACTIVE'}));assert.equal(r.statusCode,409);assert.equal(r.body.error,'INVOICE_ALREADY_SETTLED_DIFFERENT_EVIDENCE');});
test('non-primary settlement fails closed',async()=>{const r=await invoke(sqlFixture({memberType:'HOUSEHOLD_BENEFICIARY'}));assert.equal(r.statusCode,409);assert.equal(r.body.error,'PRIMARY_SUBSCRIPTION_REQUIRED');});
test('VOID invoice fails closed',async()=>{const r=await invoke(sqlFixture({invoiceState:'VOID'}));assert.equal(r.statusCode,409);assert.equal(r.body.error,'SUBSCRIPTION_INVOICE_NOT_OPEN');});
test('ACTIVE paid-standing membership cannot activate from OPEN invoice',async()=>{const r=await invoke(sqlFixture({membershipState:'ACTIVE',standing:'ACTIVE'}));assert.equal(r.statusCode,409);assert.equal(r.body.error,'MEMBERSHIP_NOT_ACTIVATABLE');});
test('INITIAL_FEE_DUE continuation can settle',async()=>{const r=await invoke(sqlFixture({membershipState:'ACTIVE',standing:'INITIAL_FEE_DUE',publicMemberId:'WFC-P-EMPLOYEE'}));assert.equal(r.statusCode,200);});
test('compare-and-set loss fails closed',async()=>{const r=await invoke(sqlFixture({atomicWins:false}));assert.equal(r.statusCode,409);assert.equal(r.body.error,'SUBSCRIPTION_SETTLEMENT_ATOMIC_RACE');});
test('database invariant abort fails closed',async()=>{const r=await invoke(sqlFixture({atomicError:true}));assert.equal(r.statusCode,503);assert.equal(r.body.error,'SUBSCRIPTION_SETTLEMENT_FAILED');});
test('SUSPENDED PRIMARY may reactivate after settlement',async()=>{const r=await invoke(sqlFixture({membershipState:'SUSPENDED'}));assert.equal(r.statusCode,200);});
