import test from 'node:test';import assert from 'node:assert/strict';
import {CanonicalRecordLog,RebuildableProjection,memberProjection,inventoryProjection,fulfillmentProjection,savingsProjection,snapshotDigest,assertFresh} from '../../dist/packages/projections/src/index.js';
const at='2026-09-07T12:00:00Z';
const r=(stream,sequence,recordId,payload)=>({stream,sequence,recordId,occurredAt:at,payload});

test('INV-029 operational projections are disposable and drop/rebuild equivalent',()=>{const log=new CanonicalRecordLog();log.append(r('membership',1,'m1',{kind:'MEMBERSHIP',participantId:'p1',state:'ACTIVE'}));log.append(r('inventory',2,'l1',{kind:'LOT_RECEIVED',lotId:'lot1',specificationId:'rice',quantity:5}));log.append(r('inventory',3,'q1',{kind:'QUALITY',lotId:'lot1',state:'ACCEPTED'}));log.append(r('inventory',4,'a1',{kind:'ALLOCATION',lotId:'lot1',quantity:2}));log.append(r('fulfillment',5,'o1',{kind:'OBLIGATION_OPENED',obligationId:'o1',quantity:5}));log.append(r('fulfillment',6,'ac1',{kind:'ACCEPTANCE',obligationId:'o1',quantity:3}));log.append(r('economics',7,'s1',{kind:'SAVINGS',obligationId:'o1',entryId:'s1',minor:-200n,currency:'GHS'}));for(const definition of [memberProjection,inventoryProjection,fulfillmentProjection,savingsProjection]){const p=new RebuildableProjection(definition);const first=p.rebuild(log.all(),at);const digest=snapshotDigest(first);p.drop();assert.equal(p.snapshot().rows.size,0);const rebuilt=p.rebuild(log.all(),at);assert.equal(snapshotDigest(rebuilt),digest);assertFresh(rebuilt,log.all());}});

test('projection exposes stale checkpoint instead of pretending current truth',()=>{const log=new CanonicalRecordLog();log.append(r('membership',1,'m1',{kind:'MEMBERSHIP',participantId:'p1',state:'ACTIVE'}));const p=new RebuildableProjection(memberProjection);const snap=p.rebuild(log.all(),at);assertFresh(snap,log.all());log.append(r('membership',2,'m2',{kind:'MEMBERSHIP',participantId:'p1',state:'SUSPENDED'}));assert.throws(()=>assertFresh(snap,log.all()),/PROJECTION_STALE/);assert.equal(p.get('p1').membershipState,'ACTIVE');const rebuilt=p.rebuild(log.all(),at);assert.equal(rebuilt.rows.get('p1').membershipState,'SUSPENDED');});

test('inventory projection cannot make quarantined quantity available',()=>{const p=new RebuildableProjection(inventoryProjection);const source=[r('inventory',1,'l1',{kind:'LOT_RECEIVED',lotId:'lot1',specificationId:'rice',quantity:5}),r('inventory',2,'q1',{kind:'QUALITY',lotId:'lot1',state:'ACCEPTED'}),r('inventory',3,'q2',{kind:'QUALITY',lotId:'lot1',state:'QUARANTINED'})];const snap=p.rebuild(source,at);assert.equal(snap.rows.get('lot1').availableQuantity,0);});

test('savings correction projection preserves source lineage and latest signed value',()=>{const p=new RebuildableProjection(savingsProjection);const source=[r('economics',1,'r1',{kind:'SAVINGS',obligationId:'o1',entryId:'s1',minor:100n,currency:'GHS'}),r('economics',2,'r2',{kind:'SAVINGS',obligationId:'o1',entryId:'s2',minor:-50n,currency:'GHS',supersedes:'s1'})];const row=p.rebuild(source,at).rows.get('o1');assert.equal(row.savingsMinor,-50n);assert.deepEqual(row.sourceRecordIds,['r1','r2']);});

test('projection cannot create canonical records or mutate canonical log by rebuilding',()=>{const log=new CanonicalRecordLog();log.append(r('membership',1,'m1',{kind:'MEMBERSHIP',participantId:'p1',state:'ACTIVE'}));const before=log.all();const p=new RebuildableProjection(memberProjection);p.rebuild(before,at);p.drop();p.rebuild(before,at);assert.equal(log.all().length,1);assert.equal(log.all()[0].recordId,'m1');});
