import test from 'node:test';
import assert from 'node:assert/strict';
import {asId,quantity,money} from '../../dist/packages/kernel/src/index.js';
import {InMemoryFulfillmentLedger} from '../../dist/packages/fulfillment/src/index.js';
import {InMemoryRemedyLedger} from '../../dist/packages/remedy/src/index.js';
import {InMemoryObligationResolutionLedger} from '../../dist/packages/resolution/src/index.js';
import {InMemoryDemandCommitmentLedger} from '../../dist/packages/demand/src/index.js';
const pid=x=>asId(x),oid=x=>asId(x),sid=x=>asId(x),eid=x=>asId(x),cid=x=>asId(x),ofid=x=>asId(x);
const obligation={id:oid('obl:11a'),participantId:pid('member:1'),beneficiary:pid('member:1'),specificationId:sid('spec:rice'),quantity:quantity(5,'kg')};
function ready(resolution=new InMemoryObligationResolutionLedger(),to=obligation.beneficiary){const l=new InMemoryFulfillmentLedger(resolution);const a={allocationId:'a:11a',lotId:asId('lot:11a'),obligationId:obligation.id,specificationId:obligation.specificationId,quantity:quantity(5,'kg')};const w=(id,state,supersedes)=>({id,allocationId:a.allocationId,lotId:a.lotId,obligationId:a.obligationId,specificationId:a.specificationId,quantity:quantity(5,'kg'),state,operatorId:pid('operator'),placeId:'pickup:1',occurredAt:'2026-09-07T12:00:00Z',evidenceIds:[eid(`ev:${id}`)],...(supersedes?{supersedes}:{})});l.recordWork(w('pick','PICKED'),a);l.recordWork(w('pack','PACKED','pick'),a);l.recordWork(w('ready','READY_FOR_PICKUP','pack'),a);return {l,h:{id:'handover:1',fulfillmentWorkId:'ready',obligationId:obligation.id,fromCustodianId:pid('club'),toParticipantId:to,placeId:'pickup:1',handedOverAt:'2026-09-07T12:10:00Z',evidenceIds:[eid('ev:handover')]}};}
test('A same physical fulfillment work cannot be handed over twice',()=>{const {l,h}=ready();l.handover(h,obligation);assert.throws(()=>l.handover({...h,id:'handover:2'},obligation),/HANDOVER_ALREADY_RECORDED/);});
test('B handover is single-consumption and acceptance is bounded at write time',()=>{const {l,h}=ready();l.handover(h,obligation);l.accept({id:'acc:1',handoverId:h.id,obligationId:obligation.id,participantId:obligation.beneficiary,state:'PARTIALLY_ACCEPTED',quantity:quantity(3,'kg'),acceptedAt:'2026-09-07T12:11:00Z',evidenceIds:[eid('ev:acc1')]},obligation);assert.throws(()=>l.accept({id:'acc:2',handoverId:h.id,obligationId:obligation.id,participantId:obligation.beneficiary,state:'ACCEPTED',quantity:quantity(2,'kg'),acceptedAt:'2026-09-07T12:12:00Z',evidenceIds:[eid('ev:acc2')]},obligation),/HANDOVER_ALREADY_ACCEPTED/);});
test('C physical handover cannot target anyone other than obligation beneficiary',()=>{const {l,h}=ready(new InMemoryObligationResolutionLedger(),pid('random:stranger'));assert.throws(()=>l.handover(h,obligation),/HANDOVER_BENEFICIARY_MISMATCH/);});
test('D one accepted checkout command/event pair cannot create two obligations',async()=>{const verifier={isAccepted:async()=>true};const l=new InMemoryDemandCommitmentLedger(verifier);const member={id:'membership:1',participantId:pid('member:1'),state:'ACTIVE',establishedAt:'2026-09-01T00:00:00Z',eligibilityPolicyVersion:'v1',eligibilityEvidenceIds:[eid('ev:member')]};const offer={id:ofid('offer:1'),offerorId:pid('club'),specificationId:sid('spec:rice'),quantity:quantity(5,'kg'),memberPrice:money(5000n,'GHS'),priceBasis:quantity(5,'kg'),pickupPlace:'pickup:1',validFrom:'2026-09-01T00:00:00Z',validUntil:'2026-09-30T00:00:00Z',priceEvidenceIds:[eid('ev:price')],policyVersions:['v1']};const base={participantId:member.participantId,membership:member,offer,quantity:quantity(5,'kg'),authorizedCommandId:cid('cmd:checkout'),authorizedEventId:'event:checkout',acceptedAt:'2026-09-07T10:00:00Z',policyVersions:['v1']};await l.commitPurchase({...base,obligationId:oid('obl:first')});await assert.rejects(()=>l.commitPurchase({...base,obligationId:oid('obl:second')}),/AUTHORIZED_COMMITMENT_ALREADY_CONSUMED/);});
test('E goods and remedy share one write-side conservation boundary',()=>{const resolution=new InMemoryObligationResolutionLedger();const {l,h}=ready(resolution);const r=new InMemoryRemedyLedger(resolution);l.handover(h,obligation);l.accept({id:'acc:full',handoverId:h.id,obligationId:obligation.id,participantId:obligation.beneficiary,state:'ACCEPTED',quantity:quantity(5,'kg'),acceptedAt:'2026-09-07T12:11:00Z',evidenceIds:[eid('ev:accepted')]},obligation);assert.throws(()=>r.recordException({id:'ex:false-shortfall',obligationId:obligation.id,participantId:obligation.participantId,kind:'SHORTFALL',affectedQuantity:quantity(5,'kg'),occurredAt:'2026-09-07T12:12:00Z',evidenceIds:[eid('ev:false-shortfall')]},obligation),/EXCEPTION_EXCEEDS_UNRESOLVED_QUANTITY/);});
test('E reverse ordering also blocks later physical double-dispensation after remedy settlement',()=>{const resolution=new InMemoryObligationResolutionLedger();const r=new InMemoryRemedyLedger(resolution);r.recordException({id:'ex:full',obligationId:obligation.id,participantId:obligation.participantId,kind:'SHORTFALL',affectedQuantity:quantity(5,'kg'),occurredAt:'2026-09-07T12:01:00Z',evidenceIds:[eid('ev:shortfall')]},obligation);r.createRemedy({id:'remedy:full',sourceExceptionId:'ex:full',originalObligationId:obligation.id,participantId:obligation.participantId,kind:'REFUND',quantity:quantity(5,'kg'),createdAt:'2026-09-07T12:02:00Z',authorizedEventId:'event:refund',evidenceIds:[eid('ev:refund')],economicClassification:'REMEDY_SETTLEMENT'});r.completeRemedy({id:'remedy-complete:full',remedyObligationId:'remedy:full',quantity:quantity(5,'kg'),completedAt:'2026-09-07T12:03:00Z',evidenceIds:[eid('ev:refund-complete')]});const {l,h}=ready(resolution);l.handover(h,obligation);assert.throws(()=>l.accept({id:'acc:after-refund',handoverId:h.id,obligationId:obligation.id,participantId:obligation.beneficiary,state:'ACCEPTED',quantity:quantity(5,'kg'),acceptedAt:'2026-09-07T12:11:00Z',evidenceIds:[eid('ev:accepted')]},obligation),/OBLIGATION_OVERRESOLUTION/);});
