import test from 'node:test';import assert from 'node:assert/strict';
import{assertSettlementType,assertRestrictedPrepayment,mapExternalSemantic,migrateOptionalBoolean,migrateOptionalNumber,resolveAcceptanceConflict}from '../../dist/packages/conformance/src/frontier.js';

test('FX-010 provider delivered versus member dispute remains disputed',()=>{const x=resolveAcceptanceConflict({providerEvidenceId:'ev:courier',memberEvidenceId:'ev:member',providerSaysDelivered:true,memberAccepts:false});assert.equal(x.state,'DISPUTED');assert.equal(x.evidenceIds.length,2);});
test('FX-012 remedy credit cannot masquerade as refund',()=>assert.throws(()=>assertSettlementType('REFUND','REMEDY_CREDIT'),/SETTLEMENT_TYPE_MISMATCH/));
test('FX-016 restricted member prepayment cannot inflate deployable liquidity',()=>assert.throws(()=>assertRestrictedPrepayment({deployable:{currency:'GHS',minor:1000n},restrictedPrepayment:{currency:'GHS',minor:5000n},reportedDeployable:{currency:'GHS',minor:6000n}}),/RESTRICTED_PREPAYMENT_MISCLASSIFIED/));
test('FX-022 unknown provider semantic cannot silently enter canon',()=>assert.throws(()=>mapExternalSemantic({provider:'momo',providerVersion:'v2',externalStatus:'NEW_SUCCESS',canonicalMeaning:null,mappingVersion:'acl-1',evidenceIds:['ev:provider-contract']}),/PROVIDER_SEMANTIC_UNMAPPED/));
test('FX-022 mapped provider semantic carries provider and mapping version',()=>assert.equal(mapExternalSemantic({provider:'momo',providerVersion:'v2',externalStatus:'SUCCESS',canonicalMeaning:'PAYMENT_OBSERVED',mappingVersion:'acl-2',evidenceIds:['ev:provider-contract']}).canonicalMeaning,'PAYMENT_OBSERVED'));
test('FX-025 migration preserves unknown instead of false or zero',()=>{assert.deepEqual(migrateOptionalBoolean(null),{known:false});assert.deepEqual(migrateOptionalNumber(undefined),{known:false});assert.deepEqual(migrateOptionalBoolean(false),{known:true,value:false});assert.deepEqual(migrateOptionalNumber(0),{known:true,value:0});});
