import test from 'node:test';import assert from 'node:assert/strict';
import {asId,money,quantity} from '../../dist/packages/kernel/src/index.js';
import {SupplyDecisionLedger,PhysicalLineageLedger,ReserveLedger,authorizePricePromise,authorizeCapitalAction,CollateralLedger,EvidenceGovernanceLedger} from '../../dist/packages/governance/src/index.js';
const sid=x=>asId(x),pid=x=>asId(x),eid=x=>asId(x);const spec=sid('spec:rice');

test('INV-005 supply facets remain semantically distinct',()=>{const l=new SupplyDecisionLedger();const base={specificationId:spec,quantity:quantity(10,'kg'),place:'tema',at:'2026-09-07T10:00:00Z',evidenceIds:[eid('e1')]};const cap=l.recordFact({id:'f1',facet:'CAPACITY',...base});const avail=l.recordFact({id:'f2',facet:'AVAILABLE',...base});assert.equal(cap.facet,'CAPACITY');assert.equal(avail.facet,'AVAILABLE');assert.notEqual(cap.id,avail.id);});

test('INV-006 sourcing requires equivalent alternatives and preserves ABSTAIN',()=>{const l=new SupplyDecisionLedger();const a={mode:'BUY',specificationId:spec,quantity:quantity(10,'kg'),place:'tema',readyAt:'2026-09-10T00:00:00Z',comparableCost:money(10000n,'GHS'),evidenceIds:[eid('e1')]};assert.throws(()=>l.decide({selected:'BUY',compared:[a,{...a,mode:'IMPORT',quantity:quantity(9,'kg')}],authorityId:'auth',decidedAt:'2026-09-07T10:00:00Z'}),/NOT_EQUIVALENT/);assert.equal(l.decide({selected:'ABSTAIN',compared:[],authorityId:'auth',decidedAt:'2026-09-07T10:00:00Z'}).selected,'ABSTAIN');});

test('INV-007/008 physical transformation conserves quantity and lineage',()=>{const l=new PhysicalLineageLedger();const t=l.transform({id:'t1',kind:'PROCESS',inputLotIds:['lot:a'],outputLotIds:['lot:b'],inputQuantity:quantity(10,'kg'),outputQuantity:quantity(8,'kg'),lossQuantity:quantity(2,'kg'),occurredAt:'2026-09-07T10:00:00Z',evidenceIds:[eid('process')]});assert.deepEqual(t.inputLotIds,['lot:a']);assert.deepEqual(t.outputLotIds,['lot:b']);assert.throws(()=>l.transform({...t,id:'t2',outputQuantity:quantity(9,'kg')}),/NOT_CONSERVED/);});

test('INV-011 reserve release obeys floor and authority',()=>{const l=new ReserveLedger();l.designate({id:'r1',lotId:'lot:a',quantity:quantity(100,'kg'),purpose:'member-resilience',minimumRetained:quantity(40,'kg'),policyVersion:'reserve:v1',designatedAt:'2026-09-07T10:00:00Z',evidenceIds:[eid('reserve')]});assert.throws(()=>l.release({id:'rel1',reserveId:'r1',quantity:quantity(70,'kg'),authorityId:'auth',memberObligations:['o1'],replacementOutlook:'tight',postReleaseCoverage:quantity(30,'kg'),releasedAt:'2026-09-07T10:05:00Z',evidenceIds:[eid('release')]}),/RESERVE_FLOOR_BREACH/);});

test('INV-015 future price promise requires full bounded envelope',()=>{const p={id:'pp1',specificationId:spec,quantity:quantity(5,'kg'),place:'accra',validFrom:'2026-09-08T00:00:00Z',validUntil:'2026-09-30T00:00:00Z',ruleVersion:'pp:v1',conditions:['member active'],authorityId:'auth',evidenceIds:[eid('policy')]};assert.equal(authorizePricePromise(p).ruleVersion,'pp:v1');assert.throws(()=>authorizePricePromise({...p,conditions:[]}),/PRICE_PROMISE_BOUNDARY_REQUIRED/);});

test('INV-016 positive return cannot override liquidity or maturity constraint',()=>{const pos={deployable:money(100000n,'GHS'),restricted:money(50000n,'GHS'),minimumHeadroom:money(40000n,'GHS'),nearestMaturityAt:'2026-09-10T00:00:00Z'};const action={id:'a1',cashOutlay:money(70000n,'GHS'),expectedReturn:money(150000n,'GHS'),lockUntil:'2026-10-01T00:00:00Z',authorityId:'auth',evidenceIds:[eid('capital')]};assert.throws(()=>authorizeCapitalAction(pos,action),/LIQUIDITY_HARD_CONSTRAINT/);});

test('INV-017/018 pledged quantity reduces disposition and double pledge is rejected',()=>{const l=new CollateralLedger();l.pledge({id:'c1',lotId:'lot:a',claimantId:pid('bank:1'),quantity:quantity(70,'kg'),active:true,authorityId:'auth',evidenceIds:[eid('lien')]},quantity(100,'kg'));assert.equal(l.disposable('lot:a',quantity(100,'kg')).amount,30);assert.throws(()=>l.pledge({id:'c2',lotId:'lot:a',claimantId:pid('bank:2'),quantity:quantity(40,'kg'),active:true,authorityId:'auth',evidenceIds:[eid('lien2')]},quantity(100,'kg')),/DOUBLE_PLEDGE_REJECTED/);});

test('FX-007 / INV-022 returned food cannot auto-restock without quality determination',()=>{const l=new PhysicalLineageLedger();l.recordReturn({lotId:'return:1',parentLotId:'lot:a',quantity:quantity(2,'kg'),returnedAt:'2026-09-07T10:00:00Z',returnEvidenceIds:[eid('return')]});assert.throws(()=>l.availableReturn('return:1'),/RETURN_QUALITY_DETERMINATION_REQUIRED/);});

test('INV-023 epistemic kinds remain distinct and independent corroboration uses upstream identity',()=>{const l=new EvidenceGovernanceLedger();l.record({id:'e1',kind:'OBSERVATION',statement:'price 10',sourceId:'agent:a',upstreamIdentity:'market:1',observedAt:'2026-09-07T10:00:00Z',evidenceIds:[eid('raw1')]});l.record({id:'e2',kind:'MODEL_OUTPUT',statement:'price 10',sourceId:'model:x',upstreamIdentity:'market:1',observedAt:'2026-09-07T10:01:00Z',evidenceIds:[eid('raw2')]});assert.equal(l.corroborationCount(['e1','e2']),1);});

test('INV-025 contradiction remains explicit until governed resolution',()=>{const l=new EvidenceGovernanceLedger();const c=l.contradict({id:'x1',evidenceIds:['e1','e2'],state:'OPEN',resolutionEvidenceIds:[]});assert.equal(c.state,'OPEN');assert.throws(()=>l.contradict({id:'x2',evidenceIds:['e1','e2'],state:'RESOLVED',resolutionEvidenceIds:[]}),/CONTRADICTION_INVALID/);});

test('INV-026 material decisions preserve model, inputs, assumptions, authority and alternatives',()=>{const l=new EvidenceGovernanceLedger();const d=l.decision({id:'d1',objective:'procure rice',modelVersion:'sourcing:v3',inputs:{demand:100,season:'lean'},assumptions:['truck available'],authorityId:'auth:1',alternatives:['BUY','ABSTAIN'],constraints:['liquidity floor'],decidedAt:'2026-09-07T10:00:00Z',evidenceIds:[eid('decision')]});assert.equal(d.modelVersion,'sourcing:v3');assert.throws(()=>l.decision({...d,id:'d2',assumptions:[]}),/DECISION_RECONSTRUCTION_FIELDS_REQUIRED/);});
