import test from 'node:test';
import assert from 'node:assert/strict';
import {asId,quantity,money} from '../../dist/packages/kernel/src/index.js';
import {InMemoryDemandCommitmentLedger} from '../../dist/packages/demand/src/index.js';
import {InMemoryMembershipStore} from '../../dist/packages/membership/src/index.js';
import {InMemoryCatalog} from '../../dist/packages/catalog/src/index.js';
import {InMemoryPilotCartStore,PilotCheckoutService} from '../../dist/packages/pilot-checkout/src/index.js';

const pid=x=>asId(x),oid=x=>asId(x),sid=x=>asId(x),cid=x=>asId(x),eid=x=>asId(x);
const member=pid('participant:member');
const club=pid('participant:food-club');
const membership=(state='ACTIVE')=>({id:'membership:1',participantId:member,state,establishedAt:'2026-09-08T12:00:00Z',eligibilityPolicyVersion:'founding-worker-v1',eligibilityEvidenceIds:[eid('evidence:employment')]});
const offer=(id='offer:rice')=>({id:oid(id),offerorId:club,specificationId:sid('spec:rice'),quantity:quantity(5,'kg'),memberPrice:money(45000n,'GHS'),priceBasis:quantity(5,'kg'),pickupPlace:'Hospital Pickup A',validFrom:'2026-09-08T12:00:00Z',validUntil:'2026-09-09T12:00:00Z',priceEvidenceIds:[eid('evidence:price')],policyVersions:['member-price-v1']});

function seedMembership(store){return store.establish({id:'membership:1',participantId:member,decision:{participantId:member,eligible:true,policyVersion:'founding-worker-v1',evidenceIds:[eid('evidence:employment')],evaluatedAt:'2026-09-08T11:59:00Z',reason:'ELIGIBLE'},at:'2026-09-08T12:00:00Z'});}
function seedCatalog(catalog){catalog.publishSpecification({id:sid('spec:rice'),version:1,name:'Rice',baseUnit:'kg'});catalog.recordPriceObservation({evidenceId:eid('evidence:price'),specificationId:sid('spec:rice'),price:money(60000n,'GHS'),basis:quantity(5,'kg'),place:'Accra',observedAt:'2026-09-08T11:00:00Z',transactionLevel:'RETAIL',conditions:['cash']});return catalog.publishMemberOffer(offer());}
function setup(accepted=true){
 const ledger=new InMemoryDemandCommitmentLedger({isAccepted:async()=>accepted});
 const carts=new InMemoryPilotCartStore();
 const memberships=new InMemoryMembershipStore();seedMembership(memberships);
 const catalog=new InMemoryCatalog();seedCatalog(catalog);
 const checkout=new PilotCheckoutService(carts,ledger,memberships,catalog);
 carts.create({id:'cart:1',participantId:member,at:'2026-09-08T12:10:00Z'});
 carts.setSingleLine({cartId:'cart:1',participantId:member,offer:offer(),quantity:quantity(5,'kg'),at:'2026-09-08T12:11:00Z'});
 return {ledger,carts,checkout,memberships,catalog};
}

test('SW1-03 cart is non-binding and creates no purchase obligation',()=>{const {ledger,carts}=setup();assert.equal(carts.get('cart:1').state,'OPEN');assert.equal(ledger.getCommitment(oid('obligation:1')),undefined);});
test('SW1-03 only verified authorized checkout creates the purchase obligation',async()=>{const {ledger,carts,checkout}=setup();const commitment=await checkout.checkout({cartId:'cart:1',participantId:member,membership:membership(),offer:offer(),obligationId:oid('obligation:1'),authorizedCommandId:cid('command:checkout:1'),authorizedEventId:'event:checkout:accepted:1',acceptedAt:'2026-09-08T12:20:00Z',policyVersions:['checkout-v1']});assert.equal(commitment.obligation.state,'OPEN');assert.equal(carts.get('cart:1').state,'CHECKED_OUT');assert.equal(ledger.getCommitment(oid('obligation:1')).offerId,oid('offer:rice'));});
test('SW1-03 rejected authorization releases reservation and creates no obligation',async()=>{const {ledger,carts,checkout}=setup(false);await assert.rejects(()=>checkout.checkout({cartId:'cart:1',participantId:member,membership:membership(),offer:offer(),obligationId:oid('obligation:2'),authorizedCommandId:cid('command:checkout:2'),authorizedEventId:'event:checkout:rejected:2',acceptedAt:'2026-09-08T12:20:00Z',policyVersions:['checkout-v1']}),/AUTHORIZED_COMMITMENT_NOT_VERIFIED/);assert.equal(carts.get('cart:1').state,'OPEN');assert.equal(ledger.getCommitment(oid('obligation:2')),undefined);});
test('SW1-03 canonical membership state overrides stale caller snapshot',async()=>{const {checkout,memberships}=setup();memberships.suspend('membership:1');await assert.rejects(()=>checkout.checkout({cartId:'cart:1',participantId:member,membership:membership('ACTIVE'),offer:offer(),obligationId:oid('obligation:3'),authorizedCommandId:cid('command:checkout:3'),authorizedEventId:'event:checkout:3',acceptedAt:'2026-09-08T12:20:00Z',policyVersions:['checkout-v1']}),/PURCHASE_REQUIRES_ACTIVE_MEMBERSHIP/);});
test('SW1-03 fabricated offer snapshot cannot override canonical offer',async()=>{const {checkout}=setup();const fabricated={...offer(),specificationId:sid('spec:beans'),memberPrice:money(1n,'GHS')};const commitment=await checkout.checkout({cartId:'cart:1',participantId:member,membership:membership(),offer:fabricated,obligationId:oid('obligation:canonical-offer'),authorizedCommandId:cid('command:canonical-offer'),authorizedEventId:'event:canonical-offer',acceptedAt:'2026-09-08T12:20:00Z',policyVersions:['checkout-v1']});assert.equal(commitment.obligation.specificationId,sid('spec:rice'));assert.equal(commitment.committedMemberPrice.minor,45000n);});
test('SW1-03 non-finite cart quantity and backdated transitions fail closed',()=>{const {carts}=setup();assert.throws(()=>carts.setSingleLine({cartId:'cart:1',participantId:member,offer:offer(),quantity:{amount:Number.NaN,unit:'kg'},at:'2026-09-08T12:12:00Z'}),/CART_QUANTITY_OUT_OF_OFFER/);assert.throws(()=>carts.abandon({cartId:'cart:1',participantId:member,at:'2026-09-08T12:09:00Z'}),/CART_TIME_REGRESSION/);});
test('SW1-03 wrong cart owner and duplicate checkout fail closed',async()=>{const {carts,checkout}=setup();assert.throws(()=>carts.setSingleLine({cartId:'cart:1',participantId:pid('participant:other'),offer:offer(),quantity:quantity(1,'kg'),at:'2026-09-08T12:21:00Z'}),/CART_PARTICIPANT_MISMATCH/);await checkout.checkout({cartId:'cart:1',participantId:member,membership:membership(),offer:offer(),obligationId:oid('obligation:4'),authorizedCommandId:cid('command:checkout:4'),authorizedEventId:'event:checkout:4',acceptedAt:'2026-09-08T12:22:00Z',policyVersions:['checkout-v1']});await assert.rejects(()=>checkout.checkout({cartId:'cart:1',participantId:member,membership:membership(),offer:offer(),obligationId:oid('obligation:5'),authorizedCommandId:cid('command:checkout:5'),authorizedEventId:'event:checkout:5',acceptedAt:'2026-09-08T12:23:00Z',policyVersions:['checkout-v1']}),/CART_NOT_OPEN/);});
test('SW1-04A concurrent checkout has exactly one commitment and no orphaned obligation',async()=>{let release;const gate=new Promise(r=>{release=r});let calls=0;const ledger=new InMemoryDemandCommitmentLedger({isAccepted:async()=>{calls++;await gate;return true;}});const carts=new InMemoryPilotCartStore();const memberships=new InMemoryMembershipStore();seedMembership(memberships);const catalog=new InMemoryCatalog();seedCatalog(catalog);const checkout=new PilotCheckoutService(carts,ledger,memberships,catalog);carts.create({id:'cart:race',participantId:member,at:'2026-09-08T12:10:00Z'});carts.setSingleLine({cartId:'cart:race',participantId:member,offer:offer(),quantity:quantity(5,'kg'),at:'2026-09-08T12:11:00Z'});const first=checkout.checkout({cartId:'cart:race',participantId:member,membership:membership(),offer:offer(),obligationId:oid('obligation:A'),authorizedCommandId:cid('command:A'),authorizedEventId:'event:A',acceptedAt:'2026-09-08T12:20:00Z',policyVersions:['checkout-v1']});await Promise.resolve();await assert.rejects(()=>checkout.checkout({cartId:'cart:race',participantId:member,membership:membership(),offer:offer(),obligationId:oid('obligation:B'),authorizedCommandId:cid('command:B'),authorizedEventId:'event:B',acceptedAt:'2026-09-08T12:20:01Z',policyVersions:['checkout-v1']}),/CART_NOT_OPEN/);assert.throws(()=>carts.releaseCheckoutAfterFailure({cartId:'cart:race',participantId:member,reservationId:'command:A:event:A',at:'2026-09-08T12:20:01Z'},Symbol('external')),/CHECKOUT_RELEASE_FORBIDDEN/);release();await first;assert.equal(calls,1);assert.ok(ledger.getCommitment(oid('obligation:A')));assert.equal(ledger.getCommitment(oid('obligation:B')),undefined);assert.equal(carts.get('cart:race').checkoutObligationId,oid('obligation:A'));});
