import test from 'node:test';import assert from 'node:assert/strict';
import {asId,money,quantity} from '../../dist/packages/kernel/src/index.js';
import {InMemoryDemandCommitmentLedger} from '../../dist/packages/demand/src/index.js';
import {SandboxPaymentProvider,SandboxWebhookVerifier,PilotPaymentService} from '../../dist/packages/pilot-payments/src/index.js';
const pid=x=>asId(x),oid=x=>asId(x),off=x=>asId(x),cmd=x=>asId(x);
const offer={id:off('offer:rice'),offerorId:pid('participant:club'),specificationId:asId('spec:rice'),quantity:quantity(5,'kg'),memberPrice:money(45000n,'GHS'),priceBasis:quantity(5,'kg'),pickupPlace:'Pickup A',validFrom:'2026-09-08T10:00:00Z',validUntil:'2026-09-09T10:00:00Z',priceEvidenceIds:[asId('evidence:price')],policyVersions:['price-v1']};
async function setup(){const demand=new InMemoryDemandCommitmentLedger({isAccepted:async()=>true});const member=pid('participant:member');await demand.commitPurchase({obligationId:oid('obligation:1'),participantId:member,membership:{id:'membership:1',participantId:member,state:'ACTIVE',establishedAt:'2026-09-08T10:00:00Z',eligibilityPolicyVersion:'v1',eligibilityEvidenceIds:[asId('evidence:elig')]},offer,quantity:quantity(5,'kg'),authorizedCommandId:cmd('command:checkout'),authorizedEventId:'event:checkout',acceptedAt:'2026-09-08T10:05:00Z',policyVersions:['checkout-v1']});const provider=new SandboxPaymentProvider();const verifier=new SandboxWebhookVerifier('secret');return {demand,member,provider,service:new PilotPaymentService(provider,verifier,demand)};}
test('SW1-04 payment intent is idempotent and conflict-safe',async()=>{const {service,member}=await setup();const a=service.createIntent({obligationId:oid('obligation:1'),participantId:member,offer,idempotencyKey:'pay-1',at:'2026-09-08T10:06:00Z'});const b=service.createIntent({obligationId:oid('obligation:1'),participantId:member,offer,idempotencyKey:'pay-1',at:'2026-09-08T10:07:00Z'});assert.equal(a.providerReference,b.providerReference);assert.throws(()=>service.createIntent({obligationId:oid('obligation:1'),participantId:pid('participant:other'),offer,idempotencyKey:'pay-1',at:'2026-09-08T10:08:00Z'}),/PAYMENT_PARTICIPANT_MISMATCH/);});
test('SW1-04 forged webhook and amount tampering fail closed',async()=>{const {service,member}=await setup();const intent=service.createIntent({obligationId:oid('obligation:1'),participantId:member,offer,idempotencyKey:'pay-2',at:'2026-09-08T10:06:00Z'});const body=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});assert.throws(()=>service.reconcileWebhook({eventId:'evt-bad',rawBody:body,signature:'forged',receivedAt:'2026-09-08T10:08:00Z'}),/PAYMENT_WEBHOOK_SIGNATURE_INVALID/);const tampered=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'99999',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});assert.throws(()=>service.reconcileWebhook({eventId:'evt-tampered',rawBody:tampered,signature:`sandbox:secret:${tampered}`,receivedAt:'2026-09-08T10:08:00Z'}),/PAYMENT_AMOUNT_MISMATCH/);});
test('SW1-04 verified webhook records restricted prepayment once and replay is idempotent',async()=>{const {service,member,demand}=await setup();const intent=service.createIntent({obligationId:oid('obligation:1'),participantId:member,offer,idempotencyKey:'pay-3',at:'2026-09-08T10:06:00Z'});const body=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});const sig=`sandbox:secret:${body}`;const first=service.reconcileWebhook({eventId:'evt-ok',rawBody:body,signature:sig,receivedAt:'2026-09-08T10:08:00Z'});const second=service.reconcileWebhook({eventId:'evt-ok',rawBody:body,signature:sig,receivedAt:'2026-09-08T10:09:00Z'});assert.equal(first.evidenceId,second.evidenceId);assert.equal(first.economicTreatment,'RESTRICTED_MEMBER_PREPAYMENT');assert.equal(demand.paymentsFor(oid('obligation:1')).length,1);});
test('SW1-04 a second provider event for the same provider reference cannot duplicate economic effect',async()=>{const {service,member}=await setup();const intent=service.createIntent({obligationId:oid('obligation:1'),participantId:member,offer,idempotencyKey:'pay-4',at:'2026-09-08T10:06:00Z'});const body=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});const sig=`sandbox:secret:${body}`;service.reconcileWebhook({eventId:'evt-1',rawBody:body,signature:sig,receivedAt:'2026-09-08T10:08:00Z'});assert.throws(()=>service.reconcileWebhook({eventId:'evt-2',rawBody:body,signature:sig,receivedAt:'2026-09-08T10:09:00Z'}),/PAYMENT_PROVIDER_REFERENCE_DUPLICATE/);});