import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';import statusHandler from '../../api/membership-status.js';
const NOW=Date.parse('2026-09-18T12:00:00Z'),TOKEN='wfc_test_member_session',SESSION_ID='member-session:'+createHash('sha256').update(TOKEN).digest('hex');function response(){const result={statusCode:null,body:null,headers:{}};return{result,setHeader(n,v){result.headers[String(n).toLowerCase()]=v;return this},status(c){result.statusCode=c;return this},json(b){result.body=b;return this}}}function req(method='GET',token=TOKEN){return{method,headers:token?{authorization:`Bearer ${token}`}:{}}}const env={VERCEL_ENV:'production',PRODUCTION_APPLICATION_ACCESS_ENABLED:'true',DATABASE_URL:'postgres://test'};
function fakeSql({session=null,invoice=null}={}){return async(strings,...values)=>{const q=strings.join('?');if(q.includes('FROM member_session')){assert.equal(values[0],SESSION_ID);return session?[session]:[];}if(q.includes('FROM membership_subscription_invoice'))return invoice?[invoice]:[];throw new Error('UNEXPECTED_QUERY '+q);};}async function invoke(sql,token=TOKEN){const res=response();await statusHandler(req('GET',token),res,{now:NOW,env,sql});return res.result;}
test('membership-status rejects non-GET',async()=>{const res=response();await statusHandler(req('POST'),res,{env});assert.equal(res.result.statusCode,405);});
test('missing member session fails closed',async()=>{const r=await invoke(fakeSql());assert.equal(r.statusCode,401);assert.equal(r.body.memberAccessAvailable,false);});
test('active primary member is admitted',async()=>{const r=await invoke(fakeSql({session:{session_id:SESSION_ID,membership_id:'m1',participant_id:'p1',state:'ACTIVE',expires_at:new Date(NOW+3600000).toISOString(),membership_state:'ACTIVE',standing:'ACTIVE',member_type:'PRIMARY',public_member_id:'WFC-1'}}));assert.equal(r.statusCode,200);assert.equal(r.body.route,'MEMBER');assert.equal(r.body.memberAccessAvailable,true);assert.equal(r.body.authenticationMethod,'WFC_MEMBER_SESSION');});
test('GRACE standing retains member access',async()=>{const r=await invoke(fakeSql({session:{session_id:SESSION_ID,membership_id:'m1',participant_id:'p1',state:'ACTIVE',expires_at:new Date(NOW+3600000).toISOString(),membership_state:'ACTIVE',standing:'GRACE',member_type:'PRIMARY',public_member_id:'WFC-1'}}));assert.equal(r.body.memberAccessAvailable,true);assert.equal(r.body.standing,'GRACE');});
test('household beneficiary is ordinary member',async()=>{const r=await invoke(fakeSql({session:{session_id:SESSION_ID,membership_id:'mh',participant_id:'ph',state:'ACTIVE',expires_at:new Date(NOW+3600000).toISOString(),membership_state:'ACTIVE',standing:'ACTIVE',member_type:'HOUSEHOLD_BENEFICIARY',public_member_id:'WFC-H-1'}}));assert.equal(r.body.route,'MEMBER');assert.equal(r.body.membershipRole,'HOUSEHOLD');});
test('inactive membership remains subscription gated when invoice open',async()=>{const r=await invoke(fakeSql({session:{session_id:SESSION_ID,membership_id:'m1',participant_id:'p1',state:'ACTIVE',expires_at:new Date(NOW+3600000).toISOString(),membership_state:'INACTIVE',standing:'INITIAL_FEE_DUE',member_type:'PRIMARY',public_member_id:'WFC-1'},invoice:{invoice_id:'i1',state:'OPEN',due_at:null}}));assert.equal(r.body.memberAccessAvailable,false);assert.equal(r.body.route,'SUBSCRIPTION_DUE');});
test('sandbox payment is signaled only in preview',async()=>{const previewEnv={...env,VERCEL_ENV:'preview'};const res=response();await statusHandler(req('GET',TOKEN),res,{now:NOW,env:previewEnv,sql:fakeSql({session:{session_id:SESSION_ID,membership_id:'m1',participant_id:'p1',state:'ACTIVE',expires_at:new Date(NOW+3600000).toISOString(),membership_state:'INACTIVE',standing:'INITIAL_FEE_DUE',member_type:'PRIMARY',public_member_id:'WFC-1'},invoice:{invoice_id:'i1',state:'OPEN',due_at:null}})});assert.equal(res.result.body.sandboxPaymentAvailable,true);});
test('sandbox payment is not signaled in production',async()=>{const r=await invoke(fakeSql({session:{session_id:SESSION_ID,membership_id:'m1',participant_id:'p1',state:'ACTIVE',expires_at:new Date(NOW+3600000).toISOString(),membership_state:'INACTIVE',standing:'INITIAL_FEE_DUE',member_type:'PRIMARY',public_member_id:'WFC-1'},invoice:{invoice_id:'i1',state:'OPEN',due_at:null}}));assert.equal(r.body.sandboxPaymentAvailable,false);});
