import test from 'node:test';
import assert from 'node:assert/strict';
import {asId} from '../../dist/packages/kernel/src/index.js';
import {InMemoryAuthorityStore,InMemoryConstraintStore,AuthorityEvaluator} from '../../dist/packages/authority/src/index.js';
import {FoundingWorkerEligibilityPolicy,GovernedEligibilityDecisionStore,InMemoryMembershipStore} from '../../dist/packages/membership/src/index.js';
import {InMemoryParticipantDirectory,InMemoryIdentityBindingStore,PilotIdentityMembershipService} from '../../dist/packages/identity/src/index.js';

const pid=x=>asId(x), gid=x=>asId(x), eid=x=>asId(x);
const at='2026-09-08T12:00:00Z';

function setup(){
 const participants=new InMemoryParticipantDirectory();
 const authorityStore=new InMemoryAuthorityStore();
 const memberships=new InMemoryMembershipStore();
 const bindings=new InMemoryIdentityBindingStore();
 const eligibility=new GovernedEligibilityDecisionStore();
 const operator=pid('participant:operator');
 const member=pid('participant:member');
 participants.register({id:operator,kind:'PERSON'});
 participants.register({id:member,kind:'PERSON'});
 authorityStore.put({id:gid('grant:identity'),grantorId:pid('participant:food-club'),actorId:operator,actions:['identity.bind'],targetPrefix:'participant:',validFrom:'2026-09-01T00:00:00Z'});
 authorityStore.put({id:gid('grant:membership'),grantorId:pid('participant:food-club'),actorId:operator,actions:['membership.verify'],targetPrefix:'membership:',validFrom:'2026-09-01T00:00:00Z'});
 const service=new PilotIdentityMembershipService(participants,bindings,memberships,new AuthorityEvaluator(authorityStore),eligibility);
 return {participants,authorityStore,memberships,bindings,eligibility,service,operator,member};
}
function principal(subject='user-123',evidence=`evidence:auth:${subject}`){return {issuer:'https://auth.example',subject,authenticatedAt:'2026-09-08T11:59:00Z',providerEvidenceId:eid(evidence),assurance:'STANDARD'};}
function governedDecision(f,evidence='evidence:employment'){return f.eligibility.record(new FoundingWorkerEligibilityPolicy(),{participantId:f.member,evidenceIds:[eid(evidence)],at,attributes:{workerClass:'PUBLIC_SECTOR',verified:true}});}

test('SW1-01 external auth subject does not become Participant identity implicitly',()=>{const {bindings}=setup();assert.equal(bindings.resolve(principal()),undefined);});
test('SW1-01 identity binding requires real delegated authority',()=>{const {service,operator,member}=setup();assert.throws(()=>service.bindAuthenticatedIdentity({bindingId:'binding:1',principal:principal(),participantId:member,actorId:operator,grantIds:[],at}),/IDENTITY_BIND_UNAUTHORIZED:NO_GRANT/);const binding=service.bindAuthenticatedIdentity({bindingId:'binding:1',principal:principal(),participantId:member,actorId:operator,grantIds:[gid('grant:identity')],at});assert.equal(binding.participantId,member);assert.notEqual(principal().subject,String(member));});
test('SW1-01 same provider identity cannot be rebound to another Participant',()=>{const {service,participants,operator,member}=setup();const other=pid('participant:other');participants.register({id:other,kind:'PERSON'});service.bindAuthenticatedIdentity({bindingId:'binding:1',principal:principal(),participantId:member,actorId:operator,grantIds:[gid('grant:identity')],at});assert.throws(()=>service.bindAuthenticatedIdentity({bindingId:'binding:2',principal:principal(),participantId:other,actorId:operator,grantIds:[gid('grant:identity')],at}),/AUTH_IDENTITY_ALREADY_BOUND/);});
test('SW1-01 revoked operator authority rejects later membership verification',()=>{const f=setup();const decision=governedDecision(f);f.authorityStore.revoke(gid('grant:membership'),'2026-09-08T11:00:00Z');assert.throws(()=>f.service.establishVerifiedMembership({membershipId:'membership:1',participantId:f.member,decision,actorId:f.operator,grantIds:[gid('grant:membership')],at}),/MEMBERSHIP_VERIFY_UNAUTHORIZED:REVOKED/);});
test('SW1-01 active authenticated member requires both binding and active membership',()=>{const f=setup();const p=principal();f.service.bindAuthenticatedIdentity({bindingId:'binding:1',principal:p,participantId:f.member,actorId:f.operator,grantIds:[gid('grant:identity')],at});assert.throws(()=>f.service.resolveActiveMember(p),/ACTIVE_MEMBERSHIP_REQUIRED/);const decision=governedDecision(f);f.service.establishVerifiedMembership({membershipId:'membership:1',participantId:f.member,decision,actorId:f.operator,grantIds:[gid('grant:membership')],at});assert.equal(f.service.resolveActiveMember(p).participant.id,f.member);f.memberships.suspend('membership:1');assert.throws(()=>f.service.resolveActiveMember(p),/ACTIVE_MEMBERSHIP_REQUIRED/);});
test('SW1-04A same issuer and subject may re-authenticate with fresh provider evidence',()=>{const f=setup();const first=principal('user-123','evidence:auth:first-login');f.service.bindAuthenticatedIdentity({bindingId:'binding:1',principal:first,participantId:f.member,actorId:f.operator,grantIds:[gid('grant:identity')],at});const decision=governedDecision(f);f.service.establishVerifiedMembership({membershipId:'membership:1',participantId:f.member,decision,actorId:f.operator,grantIds:[gid('grant:membership')],at});const second={...principal('user-123','evidence:auth:second-login'),authenticatedAt:'2026-09-08T12:30:00Z'};assert.equal(f.service.resolveActiveMember(second).participant.id,f.member);assert.throws(()=>f.service.resolveActiveMember({...second,issuer:'https://evil.example'}),/AUTH_IDENTITY_NOT_BOUND/);});
test('SW1-04A issuer-subject tuple encoding cannot collide on delimiter-like content',()=>{const {bindings}=setup();const first={id:'binding:a',issuer:'https://auth.example/a',subject:'b::c',participantId:pid('participant:a'),providerEvidenceId:eid('evidence:a'),boundAt:at,boundBy:pid('participant:operator'),authorityGrantId:gid('grant:identity')};const second={id:'binding:b',issuer:'https://auth.example/a::b',subject:'c',participantId:pid('participant:b'),providerEvidenceId:eid('evidence:b'),boundAt:at,boundBy:pid('participant:operator'),authorityGrantId:gid('grant:identity')};bindings.bind(first);bindings.bind(second);assert.equal(bindings.resolve({issuer:first.issuer,subject:first.subject})?.participantId,first.participantId);assert.equal(bindings.resolve({issuer:second.issuer,subject:second.subject})?.participantId,second.participantId);});
test('review debt: canonical participant target is not double-prefixed and STOP applies',()=>{const {participants,bindings,memberships,authorityStore,eligibility,operator,member}=setup();authorityStore.put({id:gid('grant:exact'),grantorId:pid('participant:food-club'),actorId:operator,actions:['identity.bind'],targetPrefix:'participant:member',validFrom:'2026-09-01T00:00:00Z'});const constraints=new InMemoryConstraintStore();constraints.put({id:'constraint:stop-member',kind:'STOP',reason:'review-debt regression',targetPrefix:'participant:member',activeFrom:'2026-09-01T00:00:00Z'});const service=new PilotIdentityMembershipService(participants,bindings,memberships,new AuthorityEvaluator(authorityStore,constraints),eligibility);assert.throws(()=>service.bindAuthenticatedIdentity({bindingId:'binding:stopped',principal:principal('stopped'),participantId:member,actorId:operator,grantIds:[gid('grant:exact')],at}),/IDENTITY_BIND_UNAUTHORIZED:STOP_ACTIVE/);});
test('review debt: a participant cannot hold parallel active memberships',()=>{const f=setup();const first=governedDecision(f,'evidence:employment:1');f.service.establishVerifiedMembership({membershipId:'membership:1',participantId:f.member,decision:first,actorId:f.operator,grantIds:[gid('grant:membership')],at});const second=governedDecision(f,'evidence:employment:2');assert.throws(()=>f.service.establishVerifiedMembership({membershipId:'membership:2',participantId:f.member,decision:second,actorId:f.operator,grantIds:[gid('grant:membership')],at}),/ACTIVE_MEMBERSHIP_ALREADY_EXISTS/);});

test('review debt: fabricated eligibility decision cannot activate membership',()=>{const f=setup();const fabricated={participantId:f.member,eligible:true,policyVersion:'attacker-policy',evidenceIds:[eid('evidence:fake')],evaluatedAt:at,reason:'TRUST_ME'};assert.throws(()=>f.service.establishVerifiedMembership({membershipId:'membership:fake',participantId:f.member,decision:fabricated,actorId:f.operator,grantIds:[gid('grant:membership')],at}),/ELIGIBILITY_DECISION_NOT_GOVERNED/);});
test('review debt: governed eligibility cannot be altered after evaluation',()=>{const f=setup();const decision=governedDecision(f);const altered={...decision,policyVersion:'founding-worker-v999'};assert.throws(()=>f.service.establishVerifiedMembership({membershipId:'membership:altered',participantId:f.member,decision:altered,actorId:f.operator,grantIds:[gid('grant:membership')],at}),/ELIGIBILITY_DECISION_NOT_GOVERNED/);const alteredEvidence={...decision,evidenceIds:[eid('evidence:substituted')]};assert.throws(()=>f.service.establishVerifiedMembership({membershipId:'membership:altered-evidence',participantId:f.member,decision:alteredEvidence,actorId:f.operator,grantIds:[gid('grant:membership')],at}),/ELIGIBILITY_DECISION_NOT_GOVERNED/);});
test('review debt: identical identity retry returns canonical binding and conflicting retry fails closed',()=>{const f=setup();const command={bindingId:'binding:retry',principal:principal('retry'),participantId:f.member,actorId:f.operator,grantIds:[gid('grant:identity')],at};const first=f.service.bindAuthenticatedIdentity(command);assert.equal(f.service.bindAuthenticatedIdentity(command),first);assert.throws(()=>f.service.bindAuthenticatedIdentity({...command,principal:principal('retry','evidence:auth:changed')}),/AUTH_IDENTITY_ALREADY_BOUND/);});
test('review debt: identical membership retry returns canonical relationship and conflicting retry fails closed',()=>{const f=setup();const decision=governedDecision(f);const command={membershipId:'membership:retry',participantId:f.member,decision,actorId:f.operator,grantIds:[gid('grant:membership')],at};const first=f.service.establishVerifiedMembership(command);assert.equal(f.service.establishVerifiedMembership(command),first);const other=f.eligibility.record(new FoundingWorkerEligibilityPolicy(),{participantId:f.member,evidenceIds:[eid('evidence:other')],at,attributes:{workerClass:'PUBLIC_SECTOR',verified:true}});assert.throws(()=>f.service.establishVerifiedMembership({...command,decision:other}),/MEMBERSHIP_ID_CONFLICT/);});