import test from 'node:test';import assert from 'node:assert/strict';
import {asId,money,quantity} from '../../dist/packages/kernel/src/index.js';
import {InMemoryDemandCommitmentLedger} from '../../dist/packages/demand/src/index.js';
import {InMemoryAuthorityStore,AuthorityEvaluator} from '../../dist/packages/authority/src/index.js';
import {SandboxPaymentProvider,SandboxWebhookVerifier,PilotPaymentService} from '../../dist/packages/pilot-payments/src/index.js';
const pid=x=>asId(x),oid=x=>asId(x),off=x=>asId(x),cmd=x=>asId(x),gid=x=>asId(x);
const offer={id:off('offer:rice'),offerorId:pid('participant:club'),specificationId:asId('spec:rice'),quantity:quantity(5,'kg'),memberPrice:money(45000n,'GHS'),priceBasis:quantity(5,'kg'),pickupPlace:'Pickup A',validFrom:'2026-09-08T10:00:00Z',validUntil:'2026-09-09T10:00:00Z',priceEvidenceIds:[asId('evidence:price')],policyVersions:['price-v1']};
async function setup(){const demand=new InMemoryDemandCommitmentLedger({isAccepted:async()=>true});const member=pid('participant:member');await demand.commitPurchase({obligationId:oid('obligation:1'),participantId:member,membership:{id:'membership:1',participantId:member,state:'ACTIVE',establishedAt:'2026-09-08T10:00:00Z',eligibilityPolicyVersion:'v1',eligibilityEvidenceIds:[asId('evidence:elig')]},offer,quantity:quantity(5,'kg'),authorizedCommandId:cmd('command:checkout'),authorizedEventId:'event:checkout',acceptedAt:'2026-09-08T10:05:00Z',policyVersions:['checkout-v1']});const provider=new SandboxPaymentProvider();const verifier=new SandboxWebhookVerifier('secret');const store=new InMemoryAuthorityStore();const grantId=gid('grant:payment');store.put({id:grantId,grantorId:pid('participant:club'),actorId:member,actions:['payment.initiate'],targetPrefix:'obligation:',maxQuantity:5,validFrom:'2026-09-08T00:00:00Z'});const authority=new AuthorityEvaluator(store);return {demand,member,provider,verifier,authority,grantId,service:new PilotPaymentService(provider,verifier,demand,authority)};}
const ctx=(member,grantId,at='2026-09-08T10:06:00Z')=>({actorId:member,grantIds:[grantId],at});
const create=(service,member,grantId,key='pay-1',override={})=>service.createIntent(ctx(member,grantId),{obligationId:oid('obligation:1'),participantId:member,offer,idempotencyKey:key,...override});

test('SW1-04 payment intent is idempotent and conflict-safe',async()=>{const {service,member,grantId}=await setup();const a=create(service,member,grantId,'pay-1');const b=create(service,member,grantId,'pay-1');assert.equal(a.providerReference,b.providerReference);assert.throws(()=>service.createIntent(ctx(pid('participant:other'),grantId),{obligationId:oid('obligation:1'),participantId:pid('participant:other'),offer,idempotencyKey:'pay-x'}),/PAYMENT_PARTICIPANT_MISMATCH/);});

test('review debt: a different idempotency key cannot create a second full-value intent for one obligation',async()=>{const {service,member,grantId}=await setup();const a=create(service,member,grantId,'pay-a');const b=create(service,member,grantId,'pay-b');assert.equal(a.providerReference,b.providerReference);});

test('review debt: caller cannot tamper committed payment economics',async()=>{const {service,member,grantId}=await setup();const forged={...offer,memberPrice:money(1n,'GHS')};assert.throws(()=>service.createIntent(ctx(member,grantId),{obligationId:oid('obligation:1'),participantId:member,offer:forged,idempotencyKey:'pay-forged'}),/PAYMENT_OFFER_ECONOMICS_MISMATCH/);});

test('review debt: payment initiation requires current bounded authority',async()=>{const {service,member}=await setup();assert.throws(()=>service.createIntent({actorId:member,grantIds:[],at:'2026-09-08T10:06:00Z'},{obligationId:oid('obligation:1'),participantId:member,offer,idempotencyKey:'pay-noauth'}),/PAYMENT_UNAUTHORIZED:NO_GRANT/);});

test('SW1-04 forged webhook and amount tampering fail closed',async()=>{const {service,member,grantId}=await setup();const intent=create(service,member,grantId,'pay-2');const body=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});assert.throws(()=>service.reconcileWebhook({eventId:'evt-bad',rawBody:body,signature:'forged',receivedAt:'2026-09-08T10:08:00Z'}),/PAYMENT_WEBHOOK_SIGNATURE_INVALID/);const tampered=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'99999',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});assert.throws(()=>service.reconcileWebhook({eventId:'evt-tampered',rawBody:tampered,signature:`sandbox:secret:${tampered}`,receivedAt:'2026-09-08T10:08:00Z'}),/PAYMENT_AMOUNT_MISMATCH/);});

test('SW1-04 verified webhook records restricted prepayment once and replay is idempotent',async()=>{const {service,member,grantId,demand}=await setup();const intent=create(service,member,grantId,'pay-3');const body=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});const sig=`sandbox:secret:${body}`;const first=service.reconcileWebhook({eventId:'evt-ok',rawBody:body,signature:sig,receivedAt:'2026-09-08T10:08:00Z'});const second=service.reconcileWebhook({eventId:'evt-ok',rawBody:body,signature:sig,receivedAt:'2026-09-08T10:09:00Z'});assert.equal(first.evidenceId,second.evidenceId);assert.equal(first.economicTreatment,'RESTRICTED_MEMBER_PREPAYMENT');assert.equal(demand.paymentsFor(oid('obligation:1')).length,1);});

test('review debt: cached event replay is re-verified before returning a receipt',async()=>{const {service,member,grantId}=await setup();const intent=create(service,member,grantId,'pay-cache');const body=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});service.reconcileWebhook({eventId:'evt-cache',rawBody:body,signature:`sandbox:secret:${body}`,receivedAt:'2026-09-08T10:08:00Z'});assert.throws(()=>service.reconcileWebhook({eventId:'evt-cache',rawBody:body,signature:'forged',receivedAt:'2026-09-08T10:09:00Z'}),/PAYMENT_WEBHOOK_SIGNATURE_INVALID/);});

test('SW1-04A provider redelivery with a new event id returns the existing receipt',async()=>{const {service,member,grantId,demand}=await setup();const intent=create(service,member,grantId,'pay-4');const body=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});const sig=`sandbox:secret:${body}`;const first=service.reconcileWebhook({eventId:'evt-1',rawBody:body,signature:sig,receivedAt:'2026-09-08T10:08:00Z'});const redelivery=service.reconcileWebhook({eventId:'evt-2',rawBody:body,signature:sig,receivedAt:'2026-09-08T10:09:00Z'});assert.equal(redelivery.evidenceId,first.evidenceId);assert.equal(demand.paymentsFor(oid('obligation:1')).length,1);});

test('SW1-04A provider redelivery remains idempotent after payment service restart',async()=>{const {service,member,grantId,demand,provider,verifier,authority}=await setup();const intent=create(service,member,grantId,'pay-restart');const body=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});const sig=`sandbox:secret:${body}`;const first=service.reconcileWebhook({eventId:'evt-before-restart',rawBody:body,signature:sig,receivedAt:'2026-09-08T10:08:00Z'});const restarted=new PilotPaymentService(provider,verifier,demand,authority);const redelivery=restarted.reconcileWebhook({eventId:'evt-after-restart',rawBody:body,signature:sig,receivedAt:'2026-09-08T10:09:00Z'});assert.equal(redelivery.evidenceId,first.evidenceId);assert.equal(demand.paymentsFor(oid('obligation:1')).length,1);});

test('SW1-04A conflicting terminal redelivery for same provider reference fails closed',async()=>{const {service,member,grantId}=await setup();const intent=create(service,member,grantId,'pay-5');const confirmed=JSON.stringify({providerReference:intent.providerReference,status:'CONFIRMED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});service.reconcileWebhook({eventId:'evt-confirmed',rawBody:confirmed,signature:`sandbox:secret:${confirmed}`,receivedAt:'2026-09-08T10:08:00Z'});const failed=JSON.stringify({providerReference:intent.providerReference,status:'FAILED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:09:00Z'});assert.throws(()=>service.reconcileWebhook({eventId:'evt-failed',rawBody:failed,signature:`sandbox:secret:${failed}`,receivedAt:'2026-09-08T10:10:00Z'}),/PAYMENT_PROVIDER_TERMINAL_CONFLICT/);});

test('review debt: failed provider callback has no restricted-prepayment economic effect',async()=>{const {service,member,grantId,demand}=await setup();const intent=create(service,member,grantId,'pay-failed');const failed=JSON.stringify({providerReference:intent.providerReference,status:'FAILED',amountMinor:'45000',currency:'GHS',occurredAt:'2026-09-08T10:07:00Z'});const receipt=service.reconcileWebhook({eventId:'evt-only-failed',rawBody:failed,signature:`sandbox:secret:${failed}`,receivedAt:'2026-09-08T10:08:00Z'});assert.equal(receipt.economicTreatment,'NO_ECONOMIC_EFFECT');assert.equal(demand.paymentTreatment(receipt.evidenceId).classification,'NO_ECONOMIC_EFFECT');});
