import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync, sign as signData } from 'node:crypto';

import mintHandler from '../../api/employee-session.js';
import lockHandler from '../../api/employee-session-lock.js';
import { verifyEmployeeSessionTokenShape, signEmployeeSessionToken } from '../../lib/employee-session.js';

const SECRET = 'employee-session-route-test-secret-0123456789-abcdefgh';
const NOW = Date.parse('2026-09-17T12:00:00Z');
const NOW_SEC = Math.floor(NOW / 1000);
const { privateKey, publicKey } = generateKeyPairSync('rsa', { modulusLength: 2048 });
const jwk = publicKey.export({ format: 'jwk' }); Object.assign(jwk,{kid:'employee-session-test-key',alg:'RS256',use:'sig'});
const OIDC_ENV={PRODUCTION_APPLICATION_ACCESS_ENABLED:'true',OIDC_ISSUER:'https://identity.example.test/',OIDC_AUDIENCE:'workers-food-club-api',OIDC_JWKS_URI:'https://identity.example.test/.well-known/jwks.json'};
function oidcToken({sub='oidc|person-1',iatSecondsAgo=5}={}){const iat=NOW_SEC-iatSecondsAgo;const h=Buffer.from(JSON.stringify({alg:'RS256',typ:'JWT',kid:jwk.kid})).toString('base64url');const p=Buffer.from(JSON.stringify({iss:OIDC_ENV.OIDC_ISSUER,aud:OIDC_ENV.OIDC_AUDIENCE,sub,exp:NOW_SEC+3300,iat})).toString('base64url');const s=signData('RSA-SHA256',Buffer.from(`${h}.${p}`),privateKey).toString('base64url');return `${h}.${p}.${s}`;}
function response(){const result={statusCode:null,body:null,headers:{}};return{result,setHeader(n,v){result.headers[String(n).toLowerCase()]=v;return this;},status(c){result.statusCode=c;return this;},json(b){result.body=b;return this;}};}
function request(method,token,extraHeaders={}){return{method,headers:{...(token?{authorization:`Bearer ${token}`} :{}),...extraHeaders}};}
const productionOptions={now:NOW,env:OIDC_ENV,production:{now:NOW,env:OIDC_ENV,jwksResolver:async()=>({keys:[jwk]})}};
test.beforeEach(()=>{process.env.VERCEL_ENV='production';});
function fakeMintSql({binding,grants=[]}={}){const inserted=[];const sql=async(strings,...values)=>{const text=strings.join('?');if(text.includes('FROM application_identity_binding'))return binding?[binding]:[];if(text.includes('FROM application_authority_grant'))return grants;if(text.includes('INSERT INTO employee_session')){inserted.push(values);return [];}throw new Error(`UNEXPECTED_QUERY: ${text}`);};sql.inserted=inserted;return sql;}
test('employee-session mint rejects a non-fresh step-up token even though it is otherwise valid',async()=>{const res=response();await mintHandler(request('POST',oidcToken({iatSecondsAgo:45*60})),res,{...productionOptions,employeeSessionSecret:SECRET,sql:fakeMintSql()});assert.equal(res.result.statusCode,401);assert.equal(res.result.body.error,'EMPLOYEE_STEP_UP_NOT_FRESH');});
test('employee-session mint requires an existing active grant -- it never creates authority',async()=>{const res=response();await mintHandler(request('POST',oidcToken()),res,{...productionOptions,employeeSessionSecret:SECRET,sql:fakeMintSql({binding:{participant_id:'participant:1',state:'ACTIVE'},grants:[]})});assert.equal(res.result.statusCode,403);assert.equal(res.result.body.error,'NO_ACTIVE_EMPLOYEE_GRANT');});
test('employee-session mint is independent of paid membership standing',async()=>{const sql=fakeMintSql({binding:{participant_id:'participant:1',state:'ACTIVE'},grants:[{grant_id:'grant:1'}]});const res=response();await mintHandler(request('POST',oidcToken()),res,{...productionOptions,employeeSessionSecret:SECRET,sql,now:NOW});assert.equal(res.result.statusCode,201);assert.equal(res.result.body.ok,true);});
test('employee-session mint succeeds with a fresh step-up and an active grant, and the token verifies back to an inserted session id',async()=>{const sql=fakeMintSql({binding:{participant_id:'participant:1',state:'ACTIVE'},grants:[{grant_id:'grant:1'}]});const res=response();await mintHandler(request('POST',oidcToken()),res,{...productionOptions,employeeSessionSecret:SECRET,sql,now:NOW});assert.equal(res.result.statusCode,201);assert.equal(res.result.body.ok,true);const sessionId=verifyEmployeeSessionTokenShape(SECRET,res.result.body.employeeSessionToken);assert.equal(typeof sessionId,'string');assert.equal(sql.inserted.length,1);assert.equal(sql.inserted[0][0],sessionId);assert.equal(sql.inserted[0][1],'participant:1');});
test('employee-session mint fails closed when EMPLOYEE_SESSION_SECRET is not configured',async()=>{const res=response();await mintHandler(request('POST',oidcToken()),res,{...productionOptions,sql:fakeMintSql({binding:{participant_id:'p:1',state:'ACTIVE'},grants:[{grant_id:'g:1'}]})});assert.equal(res.result.statusCode,503);assert.equal(res.result.body.error,'EMPLOYEE_SESSION_NOT_CONFIGURED');});
function fakeLockSql({binding,sessions=[]}={}){return async(strings,...values)=>{const text=strings.join('?');if(text.includes('FROM application_identity_binding'))return binding?[binding]:[];if(text.includes('UPDATE employee_session')){const [,sessionId,participantId]=values;const match=sessions.find(s=>s.session_id===sessionId&&s.participant_id===participantId&&!s.revoked_at);return match?[{session_id:match.session_id}]:[];}throw new Error(`UNEXPECTED_QUERY: ${text}`);};}
test('employee-session lock rejects a token with an invalid signature',async()=>{const res=response();await lockHandler(request('POST',oidcToken(),{'x-employee-session':'wfc-employee-v1.session-x.bad-signature'}),res,{...productionOptions,employeeSessionSecret:SECRET});assert.equal(res.result.statusCode,401);});
test("employee-session lock revokes the caller's own live session",async()=>{const sessionId='session:abc';const token=signEmployeeSessionToken(SECRET,sessionId);const sql=fakeLockSql({binding:{participant_id:'participant:1'},sessions:[{session_id:sessionId,participant_id:'participant:1'}]});const res=response();await lockHandler(request('POST',oidcToken(),{'x-employee-session':token}),res,{...productionOptions,employeeSessionSecret:SECRET,sql});assert.equal(res.result.statusCode,200);assert.equal(res.result.body.locked,true);});
test('employee-session lock cannot revoke a session bound to a different participant',async()=>{const sessionId='session:abc';const token=signEmployeeSessionToken(SECRET,sessionId);const sql=fakeLockSql({binding:{participant_id:'participant:1'},sessions:[{session_id:sessionId,participant_id:'participant:someone-else'}]});const res=response();await lockHandler(request('POST',oidcToken(),{'x-employee-session':token}),res,{...productionOptions,employeeSessionSecret:SECRET,sql});assert.equal(res.result.statusCode,404);});
test('employee-session mint and lock reject non-POST methods',async()=>{const mintRes=response();await mintHandler(request('GET'),mintRes,{});assert.equal(mintRes.result.statusCode,405);const lockRes=response();await lockHandler(request('GET'),lockRes,{});assert.equal(lockRes.result.statusCode,405);});
