import test from 'node:test';
import assert from 'node:assert/strict';
import applyHandler from '../../api/membership-apply.js';
function response(){const result={statusCode:null,body:null,headers:{}};return{result,setHeader(n,v){result.headers[String(n).toLowerCase()]=v;return this},status(c){result.statusCode=c;return this},json(b){result.body=b;return this}}}
function request(method,body={},headers={}){return{method,headers,body}}
function autoSql(){const calls=[];const sql=async(strings,...values)=>{calls.push({text:strings.join('?'),values});return[{application_id:'application:test'}]};sql.calls=calls;return sql}
function manualSql(){const calls=[];const sql=async(strings,...values)=>{calls.push({text:strings.join('?'),values});return[]};sql.calls=calls;return sql}
const base=(sql,mode='AUTO')=>({env:{VERCEL_ENV:'preview',MEMBERSHIP_APPLICATION_REVIEW_MODE:mode,ANNUAL_MEMBERSHIP_FEE_MINOR:'12000'},sql,annualFeeMinor:12000});
const valid={fullName:'Ama Mensah',governmentEmployer:'Ghana Health Service',email:'AMA@example.com',contactNote:' hello '};
test('rejects non-POST',async()=>{const r=response();await applyHandler(request('GET'),r,{});assert.equal(r.result.statusCode,405)});
test('AUTO self-service needs no Authorization or Google token and provisions inactive membership plus invoice',async()=>{const sql=autoSql(),r=response();await applyHandler(request('POST',valid),r,base(sql));assert.equal(r.result.statusCode,201);assert.equal(r.result.body.reviewRequired,false);assert.equal(r.result.body.membershipProvisioned,true);assert.equal(r.result.body.membershipState,'INACTIVE');assert.equal(r.result.body.standing,'INITIAL_FEE_DUE');assert.equal(r.result.body.loginIdentityBound,false);assert.match(sql.calls[0].text,/application_membership/);assert.match(sql.calls[0].text,/membership_subscription_invoice/);assert.doesNotMatch(sql.calls[0].text,/application_identity_binding/)});
test('arbitrary Authorization header has no enrollment authority',async()=>{const r=response();await applyHandler(request('POST',valid,{authorization:'Bearer arbitrary'}),r,base(autoSql()));assert.equal(r.result.statusCode,201)});
test('MANUAL review is supported but optional',async()=>{const sql=manualSql(),r=response();await applyHandler(request('POST',valid),r,base(sql,'MANUAL'));assert.equal(r.result.statusCode,201);assert.equal(r.result.body.reviewRequired,true);assert.equal(r.result.body.membershipProvisioned,false);assert.match(sql.calls[0].text,/'MANUAL','PENDING'/)});
test('government employer is required',async()=>{const r=response();await applyHandler(request('POST',{fullName:'Ama',email:'a@example.com'}),r,base(autoSql()));assert.equal(r.result.statusCode,400);assert.equal(r.result.body.error,'GOVERNMENT_EMPLOYER_REQUIRED')});
test('email or phone is required',async()=>{const r=response();await applyHandler(request('POST',{fullName:'Ama',governmentEmployer:'GHS'}),r,base(autoSql()));assert.equal(r.result.statusCode,400);assert.equal(r.result.body.error,'EMAIL_OR_PHONE_REQUIRED')});
test('malformed email is rejected',async()=>{const r=response();await applyHandler(request('POST',{fullName:'Ama',governmentEmployer:'GHS',email:'bad'}),r,base(autoSql()));assert.equal(r.result.statusCode,400);assert.equal(r.result.body.error,'EMAIL_INVALID')});
