import test from 'node:test';
import assert from 'node:assert/strict';
import {asId,money,quantity} from '../../dist/packages/kernel/src/index.js';
import {InMemoryAuthorityStore,AuthorityEvaluator} from '../../dist/packages/authority/src/index.js';
import {InMemoryCatalog} from '../../dist/packages/catalog/src/index.js';
import {InMemoryEconomicsLedger} from '../../dist/packages/economics/src/index.js';
import {GovernedSalesWindowRegistry,PilotMemberCatalogService} from '../../dist/packages/sales/src/index.js';
const id=x=>asId(x);
const at='2026-09-08T10:00:00Z';
function fixture(){
 const operator=id('participant:operator'),club=id('participant:club'),spec=id('spec:rice-5kg'),priceEvidence=id('evidence:price'),grant=id('grant:sales');
 const authorityStore=new InMemoryAuthorityStore();authorityStore.put({id:grant,grantorId:club,actorId:operator,actions:['sales-window.configure'],targetPrefix:'sales-window:',validFrom:'2026-09-08T00:00:00Z',validUntil:'2026-09-30T00:00:00Z'});
 const catalog=new InMemoryCatalog();catalog.publishSpecification({id:spec,version:1,name:'Rice 5 kg',baseUnit:'kg'});catalog.publishListing({listingId:'listing:rice',sku:'RICE-5KG',specificationId:spec,displayName:'Rice 5 kg',active:true});catalog.recordPriceObservation({evidenceId:priceEvidence,specificationId:spec,price:money(50000n,'GHS'),basis:quantity(5,'kg'),place:'Hospital Pickup A',observedAt:'2026-09-08T08:00:00Z',transactionLevel:'RETAIL',conditions:['cash retail']});
 const offer=id('offer:rice');catalog.publishMemberOffer({id:offer,offerorId:club,specificationId:spec,quantity:quantity(5,'kg'),memberPrice:money(45000n,'GHS'),priceBasis:quantity(5,'kg'),pickupPlace:'Hospital Pickup A',validFrom:'2026-09-08T09:00:00Z',validUntil:'2026-09-08T17:00:00Z',priceEvidenceIds:[priceEvidence],policyVersions:['member-price-v1']});
 const economics=new InMemoryEconomicsLedger();economics.defineBenchmark({id:'benchmark:rice',version:1,purpose:'MEMBER_SAVINGS',specificationId:spec,quantity:quantity(5,'kg'),place:'Hospital Pickup A',serviceLevel:'PICKUP',transactionLevel:'RETAIL',validFrom:'2026-09-08T09:00:00Z',validUntil:'2026-09-08T17:00:00Z',normalizationRuleVersion:'norm-v1',availabilityRuleVersion:'availability-v1',observationEvidenceIds:[priceEvidence],definedAt:'2026-09-08T08:30:00Z'});economics.recordBenchmarkValuation({id:'valuation:rice',benchmarkId:'benchmark:rice',benchmarkVersion:1,obligationId:id('obligation:display'),specificationId:spec,quantity:quantity(5,'kg'),place:'Hospital Pickup A',serviceLevel:'PICKUP',availability:'EXECUTABLE',comparableValue:money(50000n,'GHS'),evaluatedAt:'2026-09-08T09:30:00Z',evidenceIds:[priceEvidence]});
 return {operator,grant,catalog,economics,offer,authorityStore};
}
test('SW1-02 governed window exposes only executable comparable member catalog truth',()=>{const f=fixture();const windows=new GovernedSalesWindowRegistry(new AuthorityEvaluator(f.authorityStore));windows.configure({id:'payday-1',place:'Hospital Pickup A',opensAt:'2026-09-08T09:00:00Z',closesAt:'2026-09-08T16:00:00Z',pickupStartsAt:'2026-09-08T12:00:00Z',pickupEndsAt:'2026-09-08T18:00:00Z',policyVersion:'sales-window-v1',evidenceIds:[id('evidence:window')],configuredBy:f.operator,authorityGrantId:f.grant});const view=new PilotMemberCatalogService(f.catalog,f.economics,windows).view({windowId:'payday-1',listingId:'listing:rice',offerId:f.offer,at,benchmarkValuationId:'valuation:rice'});assert.equal(view.memberPrice.minor,45000n);assert.equal(view.benchmark.value.minor,50000n);assert.equal(view.benchmark.benchmarkVersion,1);});
test('SW1-02 UI/admin access without canonical authority cannot configure a sales window',()=>{const f=fixture();const windows=new GovernedSalesWindowRegistry(new AuthorityEvaluator(new InMemoryAuthorityStore()));assert.throws(()=>windows.configure({id:'forged',place:'Hospital Pickup A',opensAt:'2026-09-08T09:00:00Z',closesAt:'2026-09-08T16:00:00Z',pickupStartsAt:'2026-09-08T12:00:00Z',pickupEndsAt:'2026-09-08T18:00:00Z',policyVersion:'sales-window-v1',evidenceIds:[id('evidence:window')],configuredBy:f.operator,authorityGrantId:f.grant}),/SALES_WINDOW_UNAUTHORIZED/);});
test('SW1-02 closed sales window fails closed even while underlying offer remains valid',()=>{const f=fixture();const windows=new GovernedSalesWindowRegistry(new AuthorityEvaluator(f.authorityStore));windows.configure({id:'short',place:'Hospital Pickup A',opensAt:'2026-09-08T09:00:00Z',closesAt:'2026-09-08T09:30:00Z',pickupStartsAt:'2026-09-08T12:00:00Z',pickupEndsAt:'2026-09-08T18:00:00Z',policyVersion:'sales-window-v1',evidenceIds:[id('evidence:window')],configuredBy:f.operator,authorityGrantId:f.grant});assert.equal(f.catalog.isOfferExecutable(f.offer,at),true);assert.throws(()=>new PilotMemberCatalogService(f.catalog,f.economics,windows).view({windowId:'short',listingId:'listing:rice',offerId:f.offer,at}),/SALES_WINDOW_CLOSED/);});
test('SW1-02 benchmark display rejects non-comparable quantity/place/spec context',()=>{const f=fixture();const windows=new GovernedSalesWindowRegistry(new AuthorityEvaluator(f.authorityStore));windows.configure({id:'payday-2',place:'Hospital Pickup A',opensAt:'2026-09-08T09:00:00Z',closesAt:'2026-09-08T16:00:00Z',pickupStartsAt:'2026-09-08T12:00:00Z',pickupEndsAt:'2026-09-08T18:00:00Z',policyVersion:'sales-window-v1',evidenceIds:[id('evidence:window')],configuredBy:f.operator,authorityGrantId:f.grant});const bad=id('evidence:bad');f.catalog.recordPriceObservation({evidenceId:bad,specificationId:id('spec:rice-5kg'),price:money(10000n,'GHS'),basis:quantity(1,'kg'),place:'Hospital Pickup A',observedAt:'2026-09-08T08:10:00Z',transactionLevel:'RETAIL',conditions:[]});assert.throws(()=>new PilotMemberCatalogService(f.catalog,f.economics,windows).view({windowId:'payday-2',listingId:'listing:rice',offerId:f.offer,at,benchmarkValuationId:'missing'}),/BENCHMARK_VALUATION_UNKNOWN/);});
