import test from 'node:test';
import assert from 'node:assert/strict';
import { generateKeyPairSync, sign as signData } from 'node:crypto';
import decideHandler from '../../api/membership-application-decide.js';
import { signEmployeeSessionToken } from '../../lib/employee-session.js';
const NOW=Date.parse('2026-09-18T12:00:00Z'), NOW_SEC=Math.floor(NOW/1000), EMPLOYEE_SESSION_SECRET='e'.repeat(32), ANNUAL_FEE_MINOR=12000;
const {privateKey,publicKey}=generateKeyPairSync('rsa',{modulusLength:2048}); const jwk=publicKey.export({format:'jwk'}); Object.assign(jwk,{kid:'membership-decide-test-key',alg:'RS256',use:'sig'});
const OIDC_ENV={PRODUCTION_APPLICATION_ACCESS_ENABLED:'true',OIDC_ISSUER:'https://identity.example.test/',OIDC_AUDIENCE:'workers-food-club-api',OIDC_JWKS_URI:'https://identity.example.test/.well-known/jwks.json'};
function oidcToken({sub='oidc|owner',iatSecondsAgo=5}={}){const iat=NOW_SEC-iatSecondsAgo,h=Buffer.from(JSON.stringify({alg:'RS256',typ:'JWT',kid:jwk.kid})).toString('base64url'),p=Buffer.from(JSON.stringify({iss:OIDC_ENV.OIDC_ISSUER,aud:OIDC_ENV.OIDC_AUDIENCE,sub,exp:NOW_SEC+3300,iat})).toString('base64url'),s=signData('RSA-SHA256',Buffer.from(`${h}.${p}`),privateKey).toString('base64url');return `${h}.${p}.${s}`;}
function response(){const result={statusCode:null,body:null,headers:{}};return{result,setHeader(n,v){result.headers[String(n).toLowerCase()]=v;return this;},status(c){result.statusCode=c;return this;},json(b){result.body=b;return this;}};}
function request(method,{token,employeeSession,body}={}){const headers={};if(token)headers.authorization=`Bearer ${token}`;if(employeeSession)headers['x-employee-session']=employeeSession;return{method,headers,body};}
const productionOptions={now:NOW,env:OIDC_ENV,production:{now:NOW,env:OIDC_ENV,jwksResolver:async()=>({keys:[jwk]})},employeeSessionSecret:EMPLOYEE_SESSION_SECRET,annualFeeMinor:ANNUAL_FEE_MINOR};
test.beforeEach(()=>{process.env.VERCEL_ENV='production';}); function validSessionToken(){return signEmployeeSessionToken(EMPLOYEE_SESSION_SECRET,'sess-decide-1');}
function fakeSql({callerBinding={participant_id:'participant:owner-1',state:'ACTIVE'},session={session_id:'sess-decide-1'},callerGrants=[{actions:['authority:owner']}],application={application_id:'application:1',issuer:'https://identity.example.test/',subject:'oidc|applicant',state:'SUBMITTED'},applicantBinding=null,rejectSucceeds=true,claimSucceeds=true}={}){const inserts=[],updates=[];let identityBindingCallCount=0;const sql=async(strings,...values)=>{const text=strings.join('?');if(text.includes('FROM application_identity_binding')){identityBindingCallCount++;return identityBindingCallCount===1?(callerBinding?[callerBinding]:[]):(applicantBinding?[applicantBinding]:[]);}if(text.includes('FROM employee_session'))return session?[session]:[];if(text.includes('FROM application_authority_grant'))return callerGrants;if(text.includes('SELECT application_id,issuer,subject,state')||text.includes('SELECT application_id, issuer, subject, state'))return application?[application]:[];if(text.includes('INSERT INTO application_participant')){inserts.push({table:'application_participant',text,values});return [];}if(text.includes('INSERT INTO application_identity_binding')){inserts.push({table:'application_identity_binding',text,values});return [];}if(text.includes('INSERT INTO application_membership')){inserts.push({table:'application_membership',text,values});return [];}if(text.includes('INSERT INTO membership_subscription_invoice')){inserts.push({table:'membership_subscription_invoice',text,values});return [];}if(text.includes('UPDATE membership_application')&&text.includes('REJECTED')){updates.push({table:'membership_application_reject',text,values});return rejectSucceeds?[{application_id:'application:1'}]:[];}if(text.includes('UPDATE membership_application')&&text.includes("state='APPROVED'")){updates.push({table:'membership_application_approve',text,values});return claimSucceeds?[{application_id:'application:1'}]:[];}if(text.includes('UPDATE membership_application')&&text.includes('resulting_membership_id')){updates.push({table:'membership_application_link',text,values});return [];}if(text.includes('UPDATE membership_application')&&text.includes("state='SUBMITTED'")){updates.push({table:'membership_application_retry',text,values});return [];}if(text.includes('UPDATE membership_subscription_invoice')){updates.push({table:'membership_subscription_invoice_update',text,values});return [];}if(text.includes('UPDATE application_membership')){updates.push({table:'application_membership_update',text,values});return [];}throw new Error(`UNEXPECTED_QUERY: ${text}`);};sql.inserts=inserts;sql.updates=updates;return sql;}
async function invoke(sql,decision='APPROVE',extra={}){const res=response();await decideHandler(request('POST',{token:oidcToken(),employeeSession:validSessionToken(),body:{applicationId:'application:1',decision}}),res,{...productionOptions,sql,...extra});return res;}
test('reject changes application only and creates no membership',async()=>{const sql=fakeSql(),res=await invoke(sql,'REJECT');assert.equal(res.result.statusCode,200);assert.equal(res.result.body.decision,'REJECT');assert.equal(sql.inserts.some(i=>i.table==='application_membership'),false);});
test('APPROVE creates INACTIVE PRIMARY membership, zero member scopes, and OPEN annual invoice',async()=>{const sql=fakeSql(),res=await invoke(sql);assert.equal(res.result.statusCode,200);assert.equal(res.result.body.membershipState,'INACTIVE');assert.equal(res.result.body.standing,'INITIAL_FEE_DUE');assert.ok(res.result.body.invoiceId);const binding=sql.inserts.find(i=>i.table==='application_identity_binding');assert.ok(binding);assert.deepEqual(binding.values[4],[]);const membership=sql.inserts.find(i=>i.table==='application_membership');assert.ok(membership);assert.match(membership.text,/'INACTIVE'/);assert.match(membership.text,/'PRIMARY'/);assert.match(membership.text,/'INITIAL_FEE_DUE'/);const invoice=sql.inserts.find(i=>i.table==='membership_subscription_invoice');assert.ok(invoice);assert.ok(invoice.values.includes(ANNUAL_FEE_MINOR));assert.match(invoice.text,/'OPEN'/);});
test('APPROVE reuses an already-bound applicant without granting member scopes',async()=>{const sql=fakeSql({applicantBinding:{participant_id:'participant:already-bound',state:'ACTIVE'}}),res=await invoke(sql);assert.equal(res.result.statusCode,200);assert.equal(res.result.body.participantId,'participant:already-bound');assert.equal(sql.inserts.some(i=>i.table==='application_participant'),false);assert.equal(sql.inserts.some(i=>i.table==='application_identity_binding'),false);});
test('APPROVE lost claim race creates no provisional membership or invoice',async()=>{const sql=fakeSql({claimSucceeds:false}),res=await invoke(sql);assert.equal(res.result.statusCode,409);assert.equal(res.result.body.error,'APPLICATION_ALREADY_DECIDED');assert.equal(sql.inserts.some(i=>i.table==='application_membership'),false);assert.equal(sql.inserts.some(i=>i.table==='membership_subscription_invoice'),false);});
test('ordinary Operator cannot decide applications',async()=>{const sql=fakeSql({callerGrants:[{actions:['operator:orders.read']}]}),res=await invoke(sql);assert.equal(res.result.statusCode,403);assert.equal(res.result.body.error,'MEMBERSHIP_DECISION_REQUIRES_OWNER_OR_ADMIN');});

test('APPROVE missing annual fee fails before creating durable applicant records',async()=>{const sql=fakeSql(),res=await invoke(sql,'APPROVE',{annualFeeMinor:0});assert.equal(res.result.statusCode,503);assert.equal(res.result.body.error,'ANNUAL_MEMBERSHIP_FEE_NOT_CONFIGURED');assert.equal(sql.inserts.length,0);});
