import test from'node:test';import assert from'node:assert/strict';import fs from'node:fs';
const api=fs.readFileSync(new URL('../../api/system-service-settings.js',import.meta.url),'utf8');const registry=fs.readFileSync(new URL('../../lib/external-service-registry.js',import.meta.url),'utf8');const truth=fs.readFileSync(new URL('../../docs/business-logic-v2/master-truth-matrix-amendment-external-services-2026-09-20.yaml',import.meta.url),'utf8');const migration=fs.readFileSync(new URL('../../packages/durability/sql/022_external_service_configuration.sql',import.meta.url),'utf8');const ui=fs.readFileSync(new URL('../../public/service-settings.js',import.meta.url),'utf8');
test('settings uses authoritative application auth and employee authority',()=>{assert.match(api,/requireApplicationAuth/);assert.match(api,/workforce:settings\.manage/);assert.match(api,/isSystemOwner/);});
test('settings lifecycle is configure test activate disable',()=>{for(const a of ['SAVE','TEST','ACTIVATE','DISABLE'])assert.match(api,new RegExp(`'${a}'`));assert.match(api,/SUCCESSFUL_CONNECTION_TEST_REQUIRED/);assert.match(api,/last_test_state='NOT_TESTED'/);});
test('activation does not rewrite or require browser credential re-entry',()=>{const activation=api.slice(api.indexOf("if(action==='ACTIVATE')"));assert.doesNotMatch(activation,/secretWriter/);assert.match(ui,/action==='SAVE'/);});
test('secrets are write-only metadata in database',()=>{assert.doesNotMatch(migration,/secret_key|api_key|auth_token|database_url/i);assert.match(api,/secretValuesReturned:false/);});
test('database is bootstrap control plane, not runtime settings service',()=>{const runtime=registry.slice(registry.indexOf('EXTERNAL_SERVICES'),registry.indexOf('BOOTSTRAP_SERVICES'));assert.doesNotMatch(runtime,/database\s*:/);assert.match(registry,/BOOTSTRAP_SERVICES=Object\.freeze\(\{database:/);assert.match(truth,/DEPLOYMENT_CONTROL_PLANE_ONLY/);});
test('truth explicitly removes secondary live funds gate',()=>{assert.match(truth,/additional_live_funds_gate: NONE/);assert.match(truth,/CONFIGURE_TEST_EXPLICITLY_ACTIVATE_FAIL_CLOSED/);});
test('connectivity schema agrees with runtime vocabulary',()=>{for(const s of ['NOT_TESTED','PASSED','FAILED']){assert.match(migration,new RegExp(s));assert.match(api,new RegExp(s));}});
