import { requireApplicationAuth } from '../lib/application-auth.js';
import { CATALOG_CAPABLE_OPERATORS } from '../lib/operator-tiers.js';
const ID=/^[A-Za-z0-9:_-]{1,120}$/;const clean=v=>typeof v==='string'?v.trim():'';
export default async function handler(req,res){
 if(!['GET','POST','DELETE'].includes(req.method)){res.setHeader('Allow','GET, POST, DELETE');return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'});}
 const principal=await requireApplicationAuth(req,res,'operator:catalog.manage',CATALOG_CAPABLE_OPERATORS);if(!principal)return;
 const cs=process.env.DATABASE_URL;if(!cs)return res.status(503).json({ok:false,error:'DATABASE_URL_MISSING'});
 try{const {neon}=await import('@neondatabase/serverless');const sql=neon(cs,{fetchOptions:{signal:AbortSignal.timeout(5000)}});const b=req.body||{};
 if(req.method==='GET'){const rows=await sql('SELECT l.listing_id,l.sku,l.display_name,l.active,l.specification_id,l.specification_version,s.name AS specification_name,s.base_unit,s.category FROM catalog_listing l JOIN catalog_specification s ON s.specification_id=l.specification_id AND s.version=l.specification_version ORDER BY s.category,l.display_name');return res.status(200).json({ok:true,listings:rows});}
 const listingId=clean(b.listingId);if(!ID.test(listingId))return res.status(400).json({ok:false,error:'LISTING_ID_INVALID'});
 if(req.method==='DELETE'){const rows=await sql('UPDATE catalog_listing SET active=false,updated_at=now() WHERE listing_id=$1 AND active=true RETURNING listing_id',[listingId]);if(!rows[0])return res.status(404).json({ok:false,error:'CATALOG_LISTING_NOT_FOUND'});return res.status(200).json({ok:true,listingId,active:false});}
 const specificationId=clean(b.specificationId),sku=clean(b.sku),displayName=clean(b.displayName),name=clean(b.specificationName),baseUnit=clean(b.baseUnit),category=clean(b.category),version=Number(b.specificationVersion);if(!ID.test(specificationId)||!sku||!displayName||!name||!baseUnit||!category||!Number.isSafeInteger(version)||version<1)return res.status(400).json({ok:false,error:'CATALOG_FIELDS_INVALID'});
 const actor=String(principal.actorId||principal.participantId||'').trim();if(!actor)return res.status(403).json({ok:false,error:'CATALOG_ACTOR_REQUIRED'});
 const current=await sql('SELECT max(version)::int AS version FROM catalog_specification WHERE specification_id=$1',[specificationId]);if(version<=Number(current[0]?.version||0))return res.status(409).json({ok:false,error:'SPECIFICATION_VERSION_NOT_ADVANCED'});
 await sql('UPDATE catalog_specification SET active=false WHERE specification_id=$1 AND active=true',[specificationId]);await sql('INSERT INTO catalog_specification(specification_id,version,name,base_unit,category,active,created_by) VALUES($1,$2,$3,$4,$5,true,$6)',[specificationId,version,name,baseUnit,category,actor]);const rows=await sql('INSERT INTO catalog_listing(listing_id,sku,specification_id,specification_version,display_name,active,created_by) VALUES($1,$2,$3,$4,$5,true,$6) RETURNING listing_id,sku,specification_id,specification_version,display_name,active',[listingId,sku,specificationId,version,displayName,actor]);return res.status(201).json({ok:true,listing:rows[0]});
 }catch(e){console.error('Catalog administration failed',{name:e?.name,code:e?.code,message:e?.message});if(e?.code==='23505')return res.status(409).json({ok:false,error:'CATALOG_CONFLICT'});return res.status(503).json({ok:false,error:'CATALOG_ADMINISTRATION_FAILED'});}}
