import { randomUUID } from 'node:crypto';
import { requireApplicationAuth } from '../lib/application-auth.js';
import { CATALOG_CAPABLE_OPERATORS } from '../lib/operator-tiers.js';
const ID=/^[A-Za-z0-9:_-]{1,120}$/;const clean=v=>typeof v==='string'?v.trim():'';const bounded=(v,max)=>v.length>0&&v.length<=max;
export default async function handler(req,res){
 if(!['GET','POST','PATCH','DELETE'].includes(req.method)){res.setHeader('Allow','GET, POST, PATCH, DELETE');return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'});}
 const principal=await requireApplicationAuth(req,res,'operator:catalog.manage',CATALOG_CAPABLE_OPERATORS);if(!principal)return;const actor=String(principal.actorId||principal.participantId||'').trim();if(!actor)return res.status(403).json({ok:false,error:'CATALOG_ACTOR_REQUIRED'});
 const cs=process.env.DATABASE_URL;if(!cs)return res.status(503).json({ok:false,error:'DATABASE_URL_MISSING'});
 try{const {neon}=await import('@neondatabase/serverless');const sql=neon(cs,{fetchOptions:{signal:AbortSignal.timeout(5000)}});const b=req.body||{},resource=b.resource==='category'?'category':'listing';
  if(req.method==='GET'){const listings=await sql`SELECT l.listing_id,l.sku,l.display_name,l.active,l.specification_id,l.specification_version,s.name AS specification_name,s.base_unit,c.category_id,c.name AS category FROM catalog_listing l JOIN catalog_specification s ON s.specification_id=l.specification_id AND s.version=l.specification_version JOIN catalog_category c ON c.category_id=s.category_id ORDER BY c.name,l.display_name`;const categories=await sql`SELECT category_id,name,active FROM catalog_category ORDER BY name`;return res.status(200).json({ok:true,listings,categories});}
  const eventId='catalog:event:'+randomUUID();
  if(resource==='category'){const categoryId=clean(b.categoryId),name=clean(b.name);if(!ID.test(categoryId))return res.status(400).json({ok:false,error:'CATEGORY_ID_INVALID'});
   if(req.method==='POST'){if(!bounded(name,120))return res.status(400).json({ok:false,error:'CATEGORY_NAME_INVALID'});const rows=await sql`WITH created AS (INSERT INTO catalog_category(category_id,name,active,created_by,updated_by) VALUES(${categoryId},${name},true,${actor},${actor}) RETURNING *), audited AS (INSERT INTO catalog_audit_event(event_id,entity_type,entity_id,action,actor_id,after_state) SELECT ${eventId},'CATEGORY',category_id,'CREATE',${actor},to_jsonb(created) FROM created) SELECT category_id,name,active FROM created`;return res.status(201).json({ok:true,category:rows[0]});}
   if(req.method==='PATCH'){if(!name&&typeof b.active!=='boolean')return res.status(400).json({ok:false,error:'CATEGORY_PATCH_EMPTY'});if(name&&!bounded(name,120))return res.status(400).json({ok:false,error:'CATEGORY_NAME_INVALID'});const active=typeof b.active==='boolean'?b.active:null;const rows=await sql`WITH prior AS (SELECT * FROM catalog_category WHERE category_id=${categoryId}), changed AS (UPDATE catalog_category SET name=COALESCE(NULLIF(${name},''),name),active=COALESCE(${active},active),updated_by=${actor},updated_at=now() WHERE category_id=${categoryId} RETURNING *), audited AS (INSERT INTO catalog_audit_event(event_id,entity_type,entity_id,action,actor_id,before_state,after_state) SELECT ${eventId},'CATEGORY',changed.category_id,CASE WHEN changed.active AND NOT prior.active THEN 'REACTIVATE' WHEN NOT changed.active AND prior.active THEN 'DEACTIVATE' ELSE 'UPDATE' END,${actor},to_jsonb(prior),to_jsonb(changed) FROM changed JOIN prior USING(category_id)) SELECT category_id,name,active FROM changed`;if(!rows[0])return res.status(404).json({ok:false,error:'CATEGORY_NOT_FOUND'});return res.status(200).json({ok:true,category:rows[0]});}
   if(req.method==='DELETE'){const rows=await sql`WITH prior AS (SELECT * FROM catalog_category WHERE category_id=${categoryId} AND active=true), changed AS (UPDATE catalog_category SET active=false,updated_by=${actor},updated_at=now() WHERE category_id=${categoryId} AND active=true RETURNING *), audited AS (INSERT INTO catalog_audit_event(event_id,entity_type,entity_id,action,actor_id,before_state,after_state) SELECT ${eventId},'CATEGORY',changed.category_id,'DEACTIVATE',${actor},to_jsonb(prior),to_jsonb(changed) FROM changed JOIN prior USING(category_id)) SELECT category_id,name,active FROM changed`;if(!rows[0])return res.status(404).json({ok:false,error:'CATEGORY_NOT_FOUND_OR_INACTIVE'});return res.status(200).json({ok:true,category:rows[0]});}
  }
  const listingId=clean(b.listingId);if(!ID.test(listingId))return res.status(400).json({ok:false,error:'LISTING_ID_INVALID'});
  if(req.method==='DELETE'){const rows=await sql`WITH prior AS (SELECT * FROM catalog_listing WHERE listing_id=${listingId} AND active=true), changed AS (UPDATE catalog_listing SET active=false,updated_by=${actor},updated_at=now() WHERE listing_id=${listingId} AND active=true RETURNING *), audited AS (INSERT INTO catalog_audit_event(event_id,entity_type,entity_id,action,actor_id,before_state,after_state) SELECT ${eventId},'LISTING',changed.listing_id,'DEACTIVATE',${actor},to_jsonb(prior),to_jsonb(changed) FROM changed JOIN prior USING(listing_id)) SELECT listing_id,sku,display_name,active FROM changed`;if(!rows[0])return res.status(404).json({ok:false,error:'CATALOG_LISTING_NOT_FOUND_OR_INACTIVE'});return res.status(200).json({ok:true,listing:rows[0]});}
  if(req.method==='PATCH'){const sku=clean(b.sku),displayName=clean(b.displayName),active=typeof b.active==='boolean'?b.active:null;if(!sku&&!displayName&&active===null)return res.status(400).json({ok:false,error:'CATALOG_PATCH_EMPTY'});if((sku&&!bounded(sku,120))||(displayName&&!bounded(displayName,200)))return res.status(400).json({ok:false,error:'CATALOG_PATCH_INVALID'});const rows=await sql`WITH prior AS (SELECT * FROM catalog_listing WHERE listing_id=${listingId}), changed AS (UPDATE catalog_listing SET sku=COALESCE(NULLIF(${sku},''),sku),display_name=COALESCE(NULLIF(${displayName},''),display_name),active=COALESCE(${active},active),updated_by=${actor},updated_at=now() WHERE listing_id=${listingId} RETURNING *), audited AS (INSERT INTO catalog_audit_event(event_id,entity_type,entity_id,action,actor_id,before_state,after_state) SELECT ${eventId},'LISTING',changed.listing_id,CASE WHEN changed.active AND NOT prior.active THEN 'REACTIVATE' WHEN NOT changed.active AND prior.active THEN 'DEACTIVATE' ELSE 'UPDATE' END,${actor},to_jsonb(prior),to_jsonb(changed) FROM changed JOIN prior USING(listing_id)) SELECT listing_id,sku,display_name,active,specification_id,specification_version FROM changed`;if(!rows[0])return res.status(404).json({ok:false,error:'CATALOG_LISTING_NOT_FOUND'});return res.status(200).json({ok:true,listing:rows[0]});}
  const specificationId=clean(b.specificationId),sku=clean(b.sku),displayName=clean(b.displayName),name=clean(b.specificationName),baseUnit=clean(b.baseUnit),categoryId=clean(b.categoryId),version=Number(b.specificationVersion);if(!ID.test(specificationId)||!ID.test(categoryId)||!bounded(sku,120)||!bounded(displayName,200)||!bounded(name,200)||!bounded(baseUnit,40)||!Number.isSafeInteger(version)||version<1)return res.status(400).json({ok:false,error:'CATALOG_FIELDS_INVALID'});const specEvent='catalog:event:'+randomUUID(),supersedeEvent='catalog:event:'+randomUUID();
  const rows=await sql`WITH candidate AS MATERIALIZED (SELECT c.category_id FROM catalog_category c WHERE c.category_id=${categoryId} AND c.active=true AND ${version} > COALESCE((SELECT max(s.version) FROM catalog_specification s WHERE s.specification_id=${specificationId}),0)), prior_listing AS MATERIALIZED (SELECT * FROM catalog_listing WHERE listing_id=${listingId}), deactivated AS (UPDATE catalog_specification SET active=false WHERE specification_id=${specificationId} AND active=true AND EXISTS(SELECT 1 FROM candidate) RETURNING *), spec AS (INSERT INTO catalog_specification(specification_id,version,name,base_unit,category_id,active,created_by) SELECT ${specificationId},${version},${name},${baseUnit},category_id,true,${actor} FROM candidate RETURNING *), listing AS (INSERT INTO catalog_listing(listing_id,sku,specification_id,specification_version,display_name,active,created_by,updated_by) SELECT ${listingId},${sku},specification_id,version,${displayName},true,${actor},${actor} FROM spec ON CONFLICT(listing_id) DO UPDATE SET sku=EXCLUDED.sku,specification_id=EXCLUDED.specification_id,specification_version=EXCLUDED.specification_version,display_name=EXCLUDED.display_name,active=true,updated_by=${actor},updated_at=now() RETURNING *), audit_old_spec AS (INSERT INTO catalog_audit_event(event_id,entity_type,entity_id,action,actor_id,before_state) SELECT ${supersedeEvent},'SPECIFICATION',specification_id||':'||version,'DEACTIVATE',${actor},to_jsonb(deactivated) FROM deactivated), audit_spec AS (INSERT INTO catalog_audit_event(event_id,entity_type,entity_id,action,actor_id,after_state) SELECT ${specEvent},'SPECIFICATION',specification_id||':'||version,'PUBLISH',${actor},to_jsonb(spec) FROM spec), audit_listing AS (INSERT INTO catalog_audit_event(event_id,entity_type,entity_id,action,actor_id,before_state,after_state) SELECT ${eventId},'LISTING',listing.listing_id,CASE WHEN prior_listing.listing_id IS NULL THEN 'CREATE' ELSE 'UPDATE' END,${actor},to_jsonb(prior_listing),to_jsonb(listing) FROM listing LEFT JOIN prior_listing USING(listing_id)) SELECT listing_id,sku,display_name,active,specification_id,specification_version FROM listing`;
  if(!rows[0]){const category=await sql`SELECT active FROM catalog_category WHERE category_id=${categoryId}`;if(!category[0]?.active)return res.status(409).json({ok:false,error:'CATEGORY_NOT_ACTIVE'});return res.status(409).json({ok:false,error:'SPECIFICATION_VERSION_NOT_ADVANCED'});}return res.status(201).json({ok:true,listing:rows[0]});
 }catch(e){console.error('Catalog administration failed',{name:e?.name,code:e?.code,message:e?.message});if(e?.code==='23505'||e?.code==='23503')return res.status(409).json({ok:false,error:'CATALOG_CONFLICT'});return res.status(503).json({ok:false,error:'CATALOG_ADMINISTRATION_FAILED'});}
}
