import { requireApplicationAuth } from '../lib/application-auth.js';
import { canonicalRuntimeMetadata, durableId, runtimeEnvironment, runtimeOwnerToken } from '../lib/durable-runtime-semantics.js';
const PREVIEW_PARTICIPANT_ID='preview:member:001',MEMBERSHIP_ID='preview:membership:001',POLICY_VERSION='preview-sandbox-v1';
const OFFER_ID_RE=/^[A-Za-z0-9:_-]{1,120}$/,REQUEST_ID_RE=/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;
function serialize(r,idempotent=false){return{obligationId:String(r.obligation_id),requestId:String(r.request_id),participantId:String(r.participant_id),membershipId:String(r.membership_id),offerId:String(r.offer_id),quantity:Number(r.quantity),unit:String(r.unit),committedPriceMinor:Number(r.committed_price_minor),currency:String(r.currency),fulfillmentMethod:String(r.fulfillment_method),state:String(r.state),acceptedAt:String(r.accepted_at),policyVersion:String(r.policy_version),idempotent};}
async function readExisting(sql,id){const r=await sql`SELECT obligation_id,request_id,participant_id,membership_id,offer_id,quantity,unit,committed_price_minor,currency,fulfillment_method,state,accepted_at,policy_version FROM preview_member_commitment WHERE request_id=${id} LIMIT 1`;return r?.[0]??null;}
function replayResponse(res,e,i){if(String(e.offer_id)!==i.offerId||String(e.participant_id)!==i.participantId||String(e.membership_id)!==i.membershipId)return res.status(409).json({ok:false,error:'COMMIT_REQUEST_REBOUND'});return res.status(200).json({ok:true,commitment:serialize(e,true)});}
export default async function handler(req,res){
 if(req.method!=='POST'){res.setHeader('Allow','POST');return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'});}if(process.env.VERCEL_ENV==='production')return res.status(403).json({ok:false,error:'SANDBOX_COMMIT_DISABLED_IN_PRODUCTION'});
 const principal=await requireApplicationAuth(req,res,'member:purchase.commit',PREVIEW_PARTICIPANT_ID);if(!principal)return;const runtime=canonicalRuntimeMetadata({principal,environment:runtimeEnvironment()}),ownerToken=runtimeOwnerToken(runtime.environment),cs=process.env.DATABASE_URL;if(!cs)return res.status(503).json({ok:false,error:'DATABASE_URL_MISSING'});
 const offerId=typeof req.body?.offerId==='string'?req.body.offerId:'',requestId=typeof req.body?.requestId==='string'?req.body.requestId:'';if(!OFFER_ID_RE.test(offerId))return res.status(400).json({ok:false,error:'OFFER_ID_INVALID'});if(!REQUEST_ID_RE.test(requestId))return res.status(400).json({ok:false,error:'REQUEST_ID_INVALID'});
 const identity={offerId,participantId:String(runtime.actorId),membershipId:MEMBERSHIP_ID};
 try{const {neon}=await import('@neondatabase/serverless');const sql=neon(cs,{fetchOptions:{signal:AbortSignal.timeout(5000)}});const existing=await readExisting(sql,requestId);if(existing)return replayResponse(res,existing,identity);const obligationId=durableId('obligation'),commandId=durableId('command'),eventId=durableId('event');
  const rows=await sql`WITH locked_offer AS (SELECT * FROM preview_member_offer WHERE offer_id=${offerId} FOR UPDATE), selected_offer AS (SELECT o.offer_id,o.unit_quantity,o.unit,o.price_minor,o.currency,o.fulfillment_method FROM locked_offer o WHERE o.status='OPEN' AND o.price_minor IS NOT NULL AND o.currency='GHS' AND (o.min_order_quantity IS NULL OR o.unit_quantity>=o.min_order_quantity) AND (o.max_order_quantity IS NULL OR o.unit_quantity<=o.max_order_quantity) AND (o.campaign_capacity IS NULL OR COALESCE((SELECT sum(c.quantity) FROM preview_member_commitment c WHERE c.offer_id=o.offer_id AND c.state<>'CANCELLED'),0)+o.unit_quantity<=o.campaign_capacity)), commitment AS (INSERT INTO preview_member_commitment(obligation_id,request_id,participant_id,membership_id,offer_id,quantity,unit,committed_price_minor,currency,fulfillment_method,state,authorized_command_id,authorized_event_id,policy_version) SELECT ${obligationId},${requestId},${runtime.actorId},${MEMBERSHIP_ID},offer_id,unit_quantity,unit,price_minor,currency,fulfillment_method,'OPEN',${commandId},${eventId},${POLICY_VERSION} FROM selected_offer RETURNING *), command_record AS (INSERT INTO durable_command_execution(idempotency_key,command_id,state,owner_token,lease_until,fence_generation,result_json,created_at,updated_at) SELECT ${requestId},${commandId},'COMMITTED',${ownerToken},now(),1,jsonb_build_object('status','ACCEPTED','obligationId',obligation_id,'eventIds',jsonb_build_array(${eventId}::text)),now(),now() FROM commitment RETURNING command_id), aggregate_record AS (INSERT INTO aggregate_version(aggregate_id,version) SELECT obligation_id,1 FROM commitment RETURNING aggregate_id), canonical_record AS (INSERT INTO canonical_event(event_id,aggregate_id,aggregate_version,event_type,payload,occurred_at) SELECT ${eventId},obligation_id,1,'PURCHASE_COMMITTED',jsonb_build_object('participantId',participant_id,'membershipId',membership_id,'offerId',offer_id,'quantity',jsonb_build_object('amount',quantity,'unit',unit),'committedPrice',jsonb_build_object('minor',committed_price_minor,'currency',currency),'fulfillmentMethod',fulfillment_method,'authorizedCommandId',authorized_command_id,'policyVersion',policy_version,'actorId',${runtime.actorId}::text,'environment',${runtime.environment}::text),accepted_at FROM commitment RETURNING event_id) SELECT c.obligation_id,c.request_id,c.participant_id,c.membership_id,c.offer_id,c.quantity,c.unit,c.committed_price_minor,c.currency,c.fulfillment_method,c.state,c.accepted_at,c.policy_version FROM commitment c JOIN command_record cr ON cr.command_id=c.authorized_command_id JOIN aggregate_record ar ON ar.aggregate_id=c.obligation_id JOIN canonical_record er ON er.event_id=c.authorized_event_id`;
  if(!rows?.[0])return res.status(409).json({ok:false,error:'OFFER_QUANTITY_OR_CAPACITY_NOT_COMMITTABLE'});return res.status(201).json({ok:true,commitment:serialize(rows[0])});
 }catch(error){if(error?.code==='23505'){try{const {neon}=await import('@neondatabase/serverless');const sql=neon(cs);const existing=await readExisting(sql,requestId);if(existing)return replayResponse(res,existing,identity);}catch{}}console.error('Sandbox commitment failed',{name:error?.name,code:error?.code,message:error?.message});return res.status(503).json({ok:false,error:'SANDBOX_COMMIT_FAILED'});}
}
