import {randomUUID} from 'node:crypto';import {requireApplicationAuth} from '../lib/application-auth.js';import {WORKFORCE_CAPABLE_OPERATORS} from '../lib/operator-tiers.js';import {isKnownWorkforceCapability,WORKFORCE_CAPABILITIES} from '../lib/workforce-domains.js';
export default async function handler(req,res){
 const principal=await requireApplicationAuth(req,res,'workforce:tasks.manage',WORKFORCE_CAPABLE_OPERATORS);if(!principal)return;
 const cs=process.env.DATABASE_URL;if(!cs)return res.status(503).json({ok:false,error:'DATABASE_URL_MISSING'});const {neon}=await import('@neondatabase/serverless');const sql=neon(cs,{fetchOptions:{signal:AbortSignal.timeout(5000)}});
 try{
  if(req.method==='GET'){const rows=await sql`SELECT t.*,COALESCE(json_agg(a) FILTER(WHERE a.assignment_id IS NOT NULL),'[]') assignments FROM workforce_task t LEFT JOIN workforce_task_assignment a ON a.task_id=t.task_id AND a.revoked_at IS NULL GROUP BY t.task_id ORDER BY t.created_at DESC LIMIT 200`;return res.status(200).json({ok:true,tasks:rows});}
  if(req.method!=='POST'){res.setHeader('Allow','GET, POST');return res.status(405).json({ok:false,error:'METHOD_NOT_ALLOWED'});}
  const {title,description='',requiredCapability,assigneeParticipantId,assigneeTeamId,dueAt}=req.body||{};if(!title||!isKnownWorkforceCapability(requiredCapability))return res.status(400).json({ok:false,error:'VALID_TASK_AND_CAPABILITY_REQUIRED'});if(Boolean(assigneeParticipantId)===Boolean(assigneeTeamId))return res.status(400).json({ok:false,error:'EXACTLY_ONE_ASSIGNEE_REQUIRED'});
  if(assigneeParticipantId){const grants=await sql`SELECT grant_id FROM application_authority_grant WHERE actor_id=${String(assigneeParticipantId)} AND (${requiredCapability}=ANY(actions) OR 'authority:owner'=ANY(actions)) AND valid_from<=now() AND (valid_until IS NULL OR valid_until>=now()) AND (revoked_at IS NULL OR revoked_at>now()) LIMIT 1`;if(grants.length!==1)return res.status(409).json({ok:false,error:'ASSIGNEE_AUTHORITY_MISSING'});}
  if(assigneeTeamId){const team=await sql`SELECT count(*)::int active_count FROM workforce_team_member WHERE team_id=${String(assigneeTeamId)} AND active=true`;if(Number(team[0]?.active_count||0)===0)return res.status(409).json({ok:false,error:'TEAM_HAS_NO_ACTIVE_MEMBERS'});const missing=await sql`SELECT tm.participant_id FROM workforce_team_member tm WHERE tm.team_id=${String(assigneeTeamId)} AND tm.active=true AND NOT EXISTS(SELECT 1 FROM application_authority_grant g WHERE g.actor_id=tm.participant_id AND (${requiredCapability}=ANY(g.actions) OR 'authority:owner'=ANY(g.actions)) AND g.valid_from<=now() AND (g.valid_until IS NULL OR g.valid_until>=now()) AND (g.revoked_at IS NULL OR g.revoked_at>now())) LIMIT 1`;if(missing.length)return res.status(409).json({ok:false,error:'TEAM_MEMBER_AUTHORITY_MISSING',participantId:String(missing[0].participant_id)});}
  const meta=WORKFORCE_CAPABILITIES[requiredCapability],taskId=`task:${randomUUID()}`,assignmentId=`assignment:${randomUUID()}`;await sql`WITH t AS(INSERT INTO workforce_task(task_id,domain,function_key,required_capability,title,description,created_by,due_at) VALUES(${taskId},${meta.domain},${meta.function},${requiredCapability},${String(title)},${String(description)},${principal.actorId},${dueAt||null}) RETURNING task_id) INSERT INTO workforce_task_assignment(assignment_id,task_id,assignee_participant_id,assignee_team_id,assigned_by) SELECT ${assignmentId},task_id,${assigneeParticipantId?String(assigneeParticipantId):null},${assigneeTeamId?String(assigneeTeamId):null},${principal.actorId} FROM t`;
  return res.status(201).json({ok:true,taskId,assignmentId,domain:meta.domain,function:meta.function,requiredCapability});
 }catch(e){console.error('workforce tasks failed',{code:e?.code,message:e?.message});return res.status(503).json({ok:false,error:'WORKFORCE_TASKS_FAILED'});}
}
